import type { AppEntry, I18nDict } from './types'

// Fixed-date Thai public holidays — ported verbatim from Code.js
// THAI_HOLIDAYS_FIXED. Month/day repeats every year, so no per-year table.
// Deliberately excludes lunar/Buddhist holidays (Makha Bucha, Visakha Bucha,
// Asalha Bucha, Buddhist Lent) and government "compensation day"
// (วันหยุดชดเชย) substitutions, since both shift yearly and are announced
// by cabinet resolution.
export const THAI_HOLIDAYS_FIXED: { month: number; day: number; name_en: string; name_th: string }[] = [
  { month: 1, day: 1, name_en: "New Year's Day", name_th: 'วันขึ้นปีใหม่' },
  { month: 4, day: 6, name_en: 'Chakri Day', name_th: 'วันจักรี' },
  { month: 4, day: 13, name_en: 'Songkran Festival', name_th: 'วันสงกรานต์' },
  { month: 4, day: 14, name_en: 'Songkran Festival', name_th: 'วันสงกรานต์' },
  { month: 4, day: 15, name_en: 'Songkran Festival', name_th: 'วันสงกรานต์' },
  { month: 5, day: 1, name_en: 'National Labor Day', name_th: 'วันแรงงานแห่งชาติ' },
  { month: 5, day: 4, name_en: 'Coronation Day', name_th: 'วันฉัตรมงคล' },
  { month: 7, day: 28, name_en: "King's Birthday", name_th: 'วันเฉลิมพระชนมพรรษา ร.10' },
  { month: 8, day: 12, name_en: "Mother's Day", name_th: 'วันแม่แห่งชาติ' },
  { month: 10, day: 13, name_en: 'King Bhumibol Memorial Day', name_th: 'วันคล้ายวันสวรรคต ร.9' },
  { month: 10, day: 23, name_en: 'Chulalongkorn Day', name_th: 'วันปิยมหาราช' },
  { month: 12, day: 5, name_en: "Father's Day", name_th: 'วันพ่อแห่งชาติ' },
  { month: 12, day: 10, name_en: 'Constitution Day', name_th: 'วันรัฐธรรมนูญ' },
  { month: 12, day: 31, name_en: "New Year's Eve", name_th: 'วันสิ้นปี' },
]

// Single source of truth for the app cards — ported verbatim from Code.js (APPS).
export const APPS: AppEntry[] = [
  {
    key: 'ememo',
    name: 'E-Memo',
    desc: 'Document control, memo issuance & approval workflow.',
    url: 'https://script.google.com/a/macros/vcb-con.com/s/AKfycbxv70XmRpmQf_9JKQsJwY_-N3oxc0llO4xQL52ycDdpW_HvaN_G1sG0GsRqePbLxROn/exec',
    icon: 'memo',
    accent: '#4fd1ff',
  },
  {
    key: 'minutes',
    name: 'Meeting Minutes',
    desc: 'Meeting records, decisions & action-item tracking.',
    url: 'https://script.google.com/a/macros/vcb-con.com/s/AKfycbxJN7olKBYqGHlaWXiVOI41fh8oZJ9lRstXZAj1DFVeiynyvfBf48xaKX5p4D19rUnr/exec',
    icon: 'minutes',
    accent: '#7ee8ff',
  },
  {
    key: 'sop',
    name: 'Standard Operating Procedures',
    desc: 'Browse, search & version-control company SOPs.',
    url: 'https://script.google.com/a/macros/vcb-con.com/s/AKfycby8FFhiGqjn2tSYaj8LjIPMHwBtkQk66hed7sq1q_tCFd7XhHeHef1_NTuv7qzJDIi8Dg/exec',
    icon: 'sop',
    accent: '#a78bfa',
  },
  {
    key: 'sysmap',
    name: 'System Map',
    desc: 'Interactive map of VCB Group systems & integrations.',
    url: 'https://script.google.com/macros/s/AKfycbyslTl8HOSLBtqFfp8lo0UBoVJGvCl7ieAxskcdl0HrDwYec7Uzj8khCjKtpC2VRRgh/exec',
    icon: 'sysmap',
    accent: '#f472b6',
  },
  {
    key: 'hr',
    name: 'HR Work Log',
    desc: 'Attendance, task logs & timesheet for the HR team.',
    url: 'https://script.google.com/macros/s/AKfycbzEg5Sn0tNnciRkWmwnsEM9cmq0NVmy6weblTLPqlAOccsDKkh9m6dmLMRVBpqspBblUA/exec',
    icon: 'hr',
    accent: '#34d399',
  },
  {
    key: 'credit',
    name: 'Credit Facility Manager',
    desc: 'Credit limits, drawdowns, requests & approvals.',
    url: 'https://script.google.com/macros/s/AKfycbytkA07aNklbDv3gKca-iI02FPCdC1Q0i3gAtE1Ls1ry9MCoIUmG_KabhCBip8C0vn91g/exec',
    icon: 'credit',
    accent: '#fbbf24',
  },
]

// EN / TH dictionary — ported verbatim from index.html I18N.
export const I18N: I18nDict = {
  en: {
    brand_sub: 'Internal Intranet Portal',
    staff: 'Staff',
    nav_menu: 'Menu',
    nav_dashboard: 'Dashboard',
    nav_applications: 'Applications',
    nav_shortcuts: 'Shortcuts',
    nav_more: 'More',
    nav_onboarding: 'Onboarding Portal',
    nav_erp: 'ERP',
    nav_zoom: 'Zoom',
    nav_ai_tavern: 'AI Tavern',
    nav_help: 'Help & Support',
    dash_sub: 'One place for every internal VCB Group application.',
    welcome_sub: "Here's what's happening across VCB Connect today.",
    good_morning: 'Good morning',
    good_afternoon: 'Good afternoon',
    good_evening: 'Good evening',
    system_online: 'System Online',
    applications: 'Applications',
    available: 'available',
    launch: 'Launch',
    footer_left: 'VCB Group · Internal Use Only',
    connecting: 'Connecting…',
    guest: 'Guest',
    settings_language: 'Language',
    settings_theme: 'Appearance',
    theme_light: 'Light',
    theme_dark: 'Dark',
    search_placeholder: 'Search applications…',
    search_empty: 'No applications match your search.',
    panel_announcements: 'Announcements',
    panel_announcements_empty: 'No announcements right now.',
    panel_calendar: 'Holiday Calendar',
    cal_dow: 'Su,Mo,Tu,We,Th,Fr,Sa',
    cal_legend_holiday: 'Holiday',
    cal_legend_weekend: 'Weekend',
    cal_legend_today: 'Today',
    cal_next_holiday: 'Next holiday: {name} ({date})',
    cal_days_away: '{n} days',
    cal_today: 'Today',
    panel_birthdays: 'Upcoming Birthdays',
    panel_birthdays_note: 'Sample data — connect a real source to replace this.',
    panel_leave: 'On Leave Today',
    panel_leave_empty: 'No one is on leave today.',
    tt_erp_desc: 'Navigate to Mango ERP — for purchase requests, cash requests & other numerical transactions',
    tt_zoom_desc: 'Join a Zoom meeting',
    tt_onboarding_desc: 'New hire onboarding & orientation',
    help_title: 'Report an issue',
    help_sub: "Tell us what happened — this goes straight to the VCB Connect team.",
    help_area_label: 'When you noticed this, what were you trying to do?',
    help_area_placeholder: 'Choose an option',
    help_area_other: 'Other / something else',
    help_message_label: 'Describe the issue',
    help_message_placeholder: "Tell us what happened and what's not working",
    help_close: 'Close',
    help_send: 'Send Report',
    admin_role: 'Admin',
    apps: {
      ememo: {
        name: 'E-Memo',
        desc: 'Document control, memo issuance & approval workflow.',
        preview:
          'Centralizes company documents and memos in one place, with a structured issuance and approval workflow so every record is version-controlled, traceable, and easy to find later.',
      },
      minutes: {
        name: 'Meeting Minutes',
        desc: 'Meeting records, decisions & action-item tracking.',
        preview:
          'Captures meeting records and decisions as they happen, then tracks the resulting action items to completion so agreements from a meeting are never lost or forgotten.',
      },
      sop: {
        name: 'Standard Operating Procedures',
        desc: 'Browse, search & version-control company SOPs.',
        preview:
          'Gives every team a single, searchable library of standard operating procedures, with version control so staff always work from the current approved process, not an outdated copy.',
      },
      sysmap: {
        name: 'System Map',
        desc: 'Interactive map of VCB Group systems & integrations.',
        preview:
          'Visualizes how the functions of each department across VCB Group connect to one another, making it easy to see how work and responsibilities link across teams at a glance.',
      },
      hr: {
        name: 'HR Work Log',
        desc: 'Attendance, task logs & timesheet for the HR team.',
        preview:
          'Lets the HR team log attendance, daily tasks, and timesheets in one system, replacing scattered spreadsheets with a single accurate record for the team’s work.',
      },
      credit: {
        name: 'Credit Facility Manager',
        desc: 'Credit limits, drawdowns, requests & approvals.',
        preview:
          'Manages the company’s bank credit facilities end to end — limits, drawdowns, requests, and approvals — giving the finance team a clear, auditable view of the company’s credit position with each bank.',
      },
    },
  },
  th: {
    brand_sub: 'พอร์ทัลอินทราเน็ตภายในองค์กร',
    staff: 'พนักงาน',
    nav_menu: 'เมนู',
    nav_dashboard: 'แดชบอร์ด',
    nav_applications: 'แอปพลิเคชัน',
    nav_shortcuts: 'ทางลัด',
    nav_more: 'เพิ่มเติม',
    nav_onboarding: 'พอร์ทัลปฐมนิเทศ',
    nav_erp: 'ERP',
    nav_zoom: 'Zoom',
    nav_ai_tavern: 'AI Tavern',
    nav_help: 'ช่วยเหลือ',
    dash_sub: 'ศูนย์รวมแอปพลิเคชันภายในของ VCB Group ไว้ในที่เดียว',
    welcome_sub: 'ความเคลื่อนไหวของ VCB Connect ในวันนี้',
    good_morning: 'สวัสดีตอนเช้า',
    good_afternoon: 'สวัสดีตอนบ่าย',
    good_evening: 'สวัสดีตอนเย็น',
    system_online: 'ระบบออนไลน์',
    applications: 'แอปพลิเคชัน',
    available: 'รายการ',
    launch: 'เปิดใช้งาน',
    footer_left: 'VCB Group · สำหรับใช้งานภายในเท่านั้น',
    connecting: 'กำลังเชื่อมต่อ…',
    guest: 'ผู้เยี่ยมชม',
    settings_language: 'ภาษา',
    settings_theme: 'ธีม',
    theme_light: 'สว่าง',
    theme_dark: 'มืด',
    search_placeholder: 'ค้นหาแอปพลิเคชัน…',
    search_empty: 'ไม่พบแอปพลิเคชันที่ค้นหา',
    panel_announcements: 'ประกาศ',
    panel_announcements_empty: 'ยังไม่มีประกาศในขณะนี้',
    panel_calendar: 'ปฏิทินวันหยุด',
    cal_dow: 'อา,จ,อ,พ,พฤ,ศ,ส',
    cal_legend_holiday: 'วันหยุด',
    cal_legend_weekend: 'เสาร์-อาทิตย์',
    cal_legend_today: 'วันนี้',
    cal_next_holiday: 'วันหยุดถัดไป: {name} ({date})',
    cal_days_away: 'อีก {n} วัน',
    cal_today: 'วันนี้',
    panel_birthdays: 'วันเกิดที่กำลังจะถึง',
    panel_birthdays_note: 'ข้อมูลตัวอย่าง — เชื่อมต่อแหล่งข้อมูลจริงเพื่อแทนที่ส่วนนี้',
    panel_leave: 'ลาวันนี้',
    panel_leave_empty: 'วันนี้ไม่มีพนักงานลา',
    tt_erp_desc: 'ไปที่ระบบ Mango ERP — สำหรับคำขอซื้อ คำขอเบิกเงินสด และธุรกรรมเชิงตัวเลขอื่น ๆ',
    tt_zoom_desc: 'เข้าร่วมประชุมผ่าน Zoom',
    tt_onboarding_desc: 'การปฐมนิเทศและต้อนรับพนักงานใหม่',
    help_title: 'แจ้งปัญหา',
    help_sub: 'บอกเราว่าเกิดอะไรขึ้น — ข้อความจะถูกส่งตรงถึงทีม VCB Connect',
    help_area_label: 'ขณะที่พบปัญหา คุณกำลังทำอะไรอยู่',
    help_area_placeholder: 'เลือกตัวเลือก',
    help_area_other: 'อื่น ๆ',
    help_message_label: 'อธิบายปัญหาที่พบ',
    help_message_placeholder: 'บอกเราว่าเกิดอะไรขึ้นและอะไรที่ใช้งานไม่ได้',
    help_close: 'ปิด',
    help_send: 'ส่งรายงาน',
    admin_role: 'แอดมิน',
    apps: {
      ememo: {
        name: 'อีเมโม',
        desc: 'ควบคุมเอกสาร การออกบันทึกข้อความ และขั้นตอนการอนุมัติ ระหว่างโครงการและสำนักงานใหญ่',
        preview:
          'รวมเอกสารและบันทึกข้อความของบริษัทไว้ในที่เดียว พร้อมขั้นตอนการออกและอนุมัติที่เป็นระบบ ทำให้ทุกฉบับมีเวอร์ชันที่ตรวจสอบย้อนกลับได้และค้นหาได้ง่ายในภายหลัง',
      },
      minutes: {
        name: 'รายงานการประชุม',
        desc: 'บันทึกการประชุม มติที่ประชุม และการติดตามงานที่ได้รับมอบหมาย',
        preview:
          'บันทึกรายละเอียดและมติที่ประชุมทันทีที่เกิดขึ้น พร้อมติดตามงานที่ได้รับมอบหมายจนเสร็จสิ้น เพื่อให้ข้อตกลงจากที่ประชุมไม่ถูกลืมหรือตกหล่น',
      },
      sop: {
        name: 'มาตรฐานการปฏิบัติงาน',
        desc: 'เรียกดู ค้นหา และควบคุมเวอร์ชันเอกสาร SOP ของบริษัท',
        preview:
          'เป็นคลังขั้นตอนการปฏิบัติงานมาตรฐานที่ค้นหาได้สำหรับทุกทีม พร้อมควบคุมเวอร์ชัน เพื่อให้พนักงานทำงานตามขั้นตอนที่อนุมัติล่าสุดเสมอ ไม่ใช่ฉบับที่ล้าสมัย',
      },
      sysmap: {
        name: 'แผนผังระบบ',
        desc: 'แผนผังเชื่อมโยงระบบและแอปพลิเคชันต่าง ๆ ของ VCB Group',
        preview:
          'แสดงภาพรวมการเชื่อมโยงหน้าที่งานของแต่ละฝ่ายทั่วทั้ง VCB Group ทำให้เห็นความเชื่อมโยงของงานและความรับผิดชอบระหว่างทีมต่าง ๆ ได้ในทันที',
      },
      hr: {
        name: 'บันทึกงานฝ่ายบุคคล',
        desc: 'การลงเวลา บันทึกงาน และตารางเวลาทำงานสำหรับทีม HR',
        preview:
          'ให้ทีม HR ลงเวลา บันทึกงานประจำวัน และจัดตารางเวลาทำงานไว้ในระบบเดียว แทนที่ไฟล์ Excel ที่กระจัดกระจาย เพื่อให้มีบันทึกข้อมูลการทำงานของทีมที่ถูกต้องและเป็นระบบ',
      },
      credit: {
        name: 'ระบบจัดการวงเงินสินเชื่อ',
        desc: 'วงเงินสินเชื่อ การเบิกถอน คำขอ และการอนุมัติ',
        preview:
          'บริหารจัดการวงเงินสินเชื่อของบริษัทกับธนาคารครบวงจร ตั้งแต่วงเงิน การเบิกถอน คำขอ ไปจนถึงการอนุมัติ ให้ทีมการเงินเห็นสถานะวงเงินสินเชื่อกับแต่ละธนาคารได้ชัดเจนและตรวจสอบย้อนกลับได้',
      },
    },
  },
}
