-- แผนผังระบบ — "หน้าที่ที่เกี่ยวข้อง" บนแผงรายละเอียดกล่องงาน
--
-- ภาพหน้าจอระบบจริงของลูกค้ามีสองบล็อกท้ายแผงรายละเอียด: RELATED FUNCTIONS
-- (ชิปรหัสฟังก์ชัน เช่น ENG-01 ENG-04) และ RELATED FORMS (ชิปเอกสาร Doc 02A…)
-- บล็อกแรกมาจาก NODE_FN ของเขา ซึ่งเป็นแผนที่ "กล่องงาน → รหัสฟังก์ชัน" ที่เรา
-- ยังไม่ได้นำเข้า ส่วนบล็อกหลังเขาไม่ได้เก็บเป็นข้อมูล แต่คำนวณสด ๆ จากแผนก
-- ของกล่อง (DOC_NODES ที่ dept ตรงกัน) จึงไม่ต้องมีตาราง
--
-- เพิ่มอย่างเดียว ไม่แตะของเดิม: 79 กล่องงาน · 158 ฟังก์ชัน เท่าเดิมทุกตัว
-- (ไฟล์แยกจาก 0070 เพราะ 0070 ถูกรันกับฐานข้อมูลจริงไปแล้ว)

create table if not exists sysmap_node_fns (
  node_id    text not null references sysmap_nodes(id) on delete cascade,
  code       text not null,
  sort_order int  not null default 0,
  primary key (node_id, code)
);
create index if not exists sysmap_node_fns_code_idx on sysmap_node_fns (code);

insert into sysmap_node_fns (node_id, code, sort_order) values
  ('n-doh-k', 'PM-19', 0),
  ('n-doh-k', 'FIN-15', 1),
  ('n-bd-pipeline', 'ENG-01', 0),
  ('n-bd-pipeline', 'ENG-04', 1),
  ('n-bid', 'ENG-03', 0),
  ('n-ebid', 'ENG-03', 0),
  ('n-ebid', 'ENG-04', 1),
  ('n-m-eng-mp', 'ENG-07', 0),
  ('n-m-eng-mp', 'ENG-09', 1),
  ('n-m-eng-mp', 'ENG-11', 2),
  ('n-m-eng-mp', 'ENG-12', 3),
  ('n-open', 'ENG-06', 0),
  ('n-open', 'ENG-08', 1),
  ('n-m-landcamp', 'PM-02', 0),
  ('n-m-open', 'PM-01', 0),
  ('n-plan', 'ENG-08', 0),
  ('n-plan', 'FIN-01', 1),
  ('n-boq', 'ENG-08', 0),
  ('n-boq', 'ENG-10', 1),
  ('n-vo-bd', 'ENG-14', 0),
  ('n-vo-bd', 'ENG-08', 1),
  ('n-pm-dash', 'PM-17', 0),
  ('n-pm-dash', 'ACC-13', 1),
  ('n-prequal', 'PO-15', 0),
  ('n-pr', 'PO-02', 0),
  ('n-pr', 'PM-05', 1),
  ('n-pr', 'ENG-15', 2),
  ('n-pr', 'ASSET-FA-06', 3),
  ('n-m-vend', 'PO-03', 0),
  ('n-m-vend', 'PO-04', 1),
  ('n-compare', 'PO-04', 0),
  ('n-m-neg', 'PO-05', 0),
  ('n-m-neg', 'PO-10', 1),
  ('n-po', 'PO-07', 0),
  ('n-po', 'ENG-16', 1),
  ('n-m-del', 'PO-08', 0),
  ('n-m-del', 'PO-09', 1),
  ('n-m-del', 'PO-11', 2),
  ('n-receive', 'ASSET-IC-02', 0),
  ('n-ic-recv', 'ASSET-IC-01', 0),
  ('n-ic-recv', 'ACC-14', 1),
  ('n-ic-recv', 'ASSET-IC-03', 2),
  ('n-ic-issue', 'ASSET-IC-01', 0),
  ('n-ic-issue', 'ACC-14', 1),
  ('n-ic-issue', 'ACC-05', 2),
  ('n-ic-xfer', 'ASSET-IC-01', 0),
  ('n-ic-xfer', 'ACC-14', 1),
  ('n-m-sub-sel', 'PO-06', 0),
  ('n-m-sub-sel', 'PO-03', 1),
  ('n-wo', 'PO-07', 0),
  ('n-wo', 'ENG-16', 1),
  ('n-m-super', 'PM-13', 0),
  ('n-m-super', 'PM-21', 1),
  ('n-m-super', 'PM-09', 2),
  ('n-m-super', 'ENG-13', 3),
  ('n-sub-prog', 'ENG-17', 0),
  ('n-sub-prog', 'PM-14', 1),
  ('n-sub-prog', 'PM-15', 2),
  ('n-m-ap-v', 'PM-14', 0),
  ('n-m-ap-v', 'ACC-01', 1),
  ('n-ap', 'ACC-01', 0),
  ('n-ap', 'ACC-02', 1),
  ('n-ap', 'ENG-17', 2),
  ('n-ap', 'ACC-08', 3),
  ('n-ap', 'HR-04', 4),
  ('n-ap', 'FIN-11', 5),
  ('n-ap-cn', 'ACC-01', 0),
  ('n-m-pay-v', 'FIN-11', 0),
  ('n-m-pay-v', 'FIN-12', 1),
  ('n-m-pay-v', 'FIN-16', 2),
  ('n-payments', 'FIN-11', 0),
  ('n-payments', 'FIN-14', 1),
  ('n-payments', 'FIN-12', 2),
  ('n-payments', 'FIN-13', 3),
  ('n-petty', 'ACC-08', 0),
  ('n-petty', 'ACC-09', 1),
  ('n-petty', 'HR-04', 2),
  ('n-petty', 'HR-11', 3),
  ('n-petty', 'HR-13', 4),
  ('n-petty', 'FIN-19', 5),
  ('n-petty', 'ENG-18', 6),
  ('n-petty', 'ASSET-FA-07', 7),
  ('n-petty', 'ASSET-FA-08', 8),
  ('n-petty', 'ASSET-IC-07', 9),
  ('n-m-petty', 'ACC-08', 0),
  ('n-m-prog', 'PM-17', 0),
  ('n-m-prog', 'PM-18', 1),
  ('n-m-prog', 'PM-03', 2),
  ('n-progress', 'PM-18', 0),
  ('n-progress', 'PM-17', 1),
  ('n-m-ar', 'ACC-04', 0),
  ('n-ar', 'ACC-04', 0),
  ('n-ar', 'ACC-05', 1),
  ('n-ar-cn', 'ACC-04', 0),
  ('n-m-chase', 'ACC-07', 0),
  ('n-m-chase', 'FIN-15', 1),
  ('n-receipt', 'ACC-06', 0),
  ('n-receipt', 'ACC-03', 1),
  ('n-gl', 'ACC-10', 0),
  ('n-gl', 'ACC-11', 1),
  ('n-gl', 'ACC-12', 2),
  ('n-gl', 'ACC-13', 3),
  ('n-gl', 'ACC-14', 4),
  ('n-gl', 'ACC-15', 5),
  ('n-gl', 'ACC-20', 6),
  ('n-gl', 'FIN-17', 7),
  ('n-m-recon', 'FIN-20', 0),
  ('n-m-tag', 'ASSET-FA-01', 0),
  ('n-fa', 'ASSET-FA-01', 0),
  ('n-fa', 'ACC-15', 1),
  ('n-maint', 'ASSET-FA-04', 0),
  ('n-maint', 'ASSET-FA-05', 1),
  ('n-maint', 'ACC-15', 2),
  ('n-m-fa-xfer', 'ASSET-FA-10', 0),
  ('n-m-fa-xfer', 'ACC-15', 1),
  ('n-fa-xfer', 'ACC-15', 0),
  ('n-disposal', 'ASSET-IC-06', 0),
  ('n-disposal', 'ASSET-FA-09', 1),
  ('n-disposal', 'ACC-05', 2),
  ('n-fuel', 'ASSET-IC-04', 0),
  ('n-fuel', 'ASSET-FA-02', 1),
  ('n-fuel', 'ASSET-FA-03', 2),
  ('n-fuel', 'ASSET-FA-13', 3),
  ('n-insurance', 'ASSET-IC-07', 0),
  ('n-insurance', 'ASSET-FA-07', 1),
  ('n-security', 'ASSET-IC-05', 0),
  ('n-m-insp', 'ASSET-IC-08', 0),
  ('n-m-insp', 'ACC-14', 1),
  ('n-m-insp', 'ACC-15', 2),
  ('n-m-ot-site', 'HR-17', 0),
  ('n-m-ot-site', 'PM-04', 1),
  ('n-m-ot-site', 'HR-05', 2),
  ('n-m-hr-ot', 'HR-06', 0),
  ('n-m-hr-ot', 'HR-05', 1),
  ('n-m-hr-ot', 'HR-16', 2),
  ('n-hr-payroll', 'HR-04', 0),
  ('n-m-hr-soc', 'HR-13', 0),
  ('n-m-hr-soc', 'ACC-18', 1),
  ('n-m-hr-soc', 'HR-04', 2),
  ('n-m-hr-eval', 'HR-07', 0),
  ('n-fin', 'ACC-12', 0),
  ('n-m-cf-forecast', 'FIN-01', 0),
  ('n-m-cf-forecast', 'FIN-02', 1),
  ('n-m-cf-forecast', 'FIN-03', 2),
  ('n-m-facility', 'FIN-04', 0),
  ('n-m-facility', 'FIN-07', 1),
  ('n-m-facility', 'FIN-05', 2),
  ('n-m-facility', 'FIN-08', 3),
  ('n-m-facility', 'FIN-03', 4),
  ('n-m-facility', 'FIN-09', 5),
  ('n-m-pn-prep', 'FIN-22', 0),
  ('n-m-pn-prep', 'FIN-05', 1),
  ('n-m-aval-prep', 'FIN-06', 0),
  ('n-m-aval-prep', 'FIN-04', 1),
  ('n-m-aval-disc', 'FIN-21', 0),
  ('n-bank-mgmt', 'FIN-20', 0),
  ('n-bank-mgmt', 'FIN-13', 1),
  ('n-bank-mgmt', 'ACC-16', 2),
  ('n-interjv', 'FIN-18', 0),
  ('n-m-vat-compile', 'ACC-17', 0),
  ('n-vat-filing', 'ACC-17', 0),
  ('n-m-wht-compile', 'ACC-18', 0),
  ('n-wht-filing', 'ACC-18', 0),
  ('n-m-cit', 'ACC-19', 0),
  ('n-m-pq', 'ENG-02', 0),
  ('n-m-pq', 'ASSET-FA-12', 1),
  ('n-m-final-claim', 'PM-22', 0),
  ('n-m-final-claim', 'ACC-04', 1),
  ('n-m-defect', 'PM-23', 0),
  ('n-m-defect', 'PM-21', 1),
  ('n-m-retention-claim', 'FIN-15', 0),
  ('n-m-retention-claim', 'PM-23', 1),
  ('n-retention-ar', 'ACC-04', 0),
  ('n-m-final-account', 'ENG-19', 0),
  ('n-m-final-account', 'ACC-13', 1),
  ('n-ar-recv-ni', 'FIN-23', 0),
  ('n-project-close', 'ENG-19', 0)
on conflict (node_id, code) do update set sort_order = excluded.sort_order;
