/**
 * English for the Thai the screens already say.
 *
 * Keyed by the Thai text itself — see lib/i18n.jsx for why. A string missing
 * from here simply stays Thai, which is what every user sees today, so this file
 * can never take the system backwards.
 *
 * Translate what a person READS, not what a database holds: project names,
 * document subjects and people's names stay exactly as they were entered.
 *
 * Grouped the way the screens are, so a gap is easy to spot.
 */
export const EN = {
  // ── ปุ่มและคำที่ใช้ทั่วทั้งระบบ ──────────────────────────────────────────
  'บันทึก': 'Save',
  'บันทึกแล้ว': 'Saved',
  'กำลังบันทึก…': 'Saving…',
  'ยกเลิก': 'Cancel',
  'ปิด': 'Close',
  'แก้ไข': 'Edit',
  'ลบ': 'Delete',
  'กำลังลบ…': 'Deleting…',
  'ลบแล้ว': 'Deleted',
  'เพิ่ม': 'Add',
  'จัดการ': 'Manage',
  'ลองใหม่': 'Try again',
  'กำลังโหลด…': 'Loading…',
  'กำลังส่ง…': 'Sending…',
  'กำลังอัปโหลด…': 'Uploading…',
  'กำลังส่งออก…': 'Exporting…',
  'ส่ง': 'Send',
  'ค้นหา…': 'Search…',
  'ทั้งหมด': 'All',
  'ไม่พบข้อมูล': 'Nothing found',
  'ยังไม่มีข้อมูล': 'No data yet',
  'ดูรายละเอียด': 'View details',
  'ดาวน์โหลด': 'Download',
  'เปิดเต็มจอ': 'Open full screen',
  'แชร์': 'Share',
  'คัดลอกแล้ว': 'Copied',
  'คัดลอกไม่สำเร็จ': 'Copy failed',
  'กำลังคัดลอก…': 'Copying…',
  'เสร็จสิ้น': 'Done',
  'ถัดไป': 'Next',
  'ย้อนกลับ': 'Back',
  'ยืนยัน': 'Confirm',
  'ตกลง': 'OK',
  'เพิ่มรายการ': 'Add row',
  'ล้างทั้งหมด': 'Clear all',

  // ── คำนามที่ใช้ร่วมกัน ─────────────────────────────────────────────────
  'โครงการ': 'Project',
  'ทุกโครงการ': 'All projects',
  'ทุกกลุ่ม': 'All groups',
  'ทุกหมวด': 'All categories',
  'ทุกแผนก': 'All departments',
  'ทุกสถานะ': 'All statuses',
  'แผนก': 'Department',
  'สถานะ': 'Status',
  'ประเภท': 'Type',
  'รหัส': 'Code',
  'ชื่อ-นามสกุล': 'Full name',
  'อีเมล': 'Email',
  'บทบาท': 'Role',
  'ตำแหน่ง': 'Position',
  'หมายเหตุ': 'Note',
  'เหตุผล': 'Reason',
  'วันที่': 'Date',
  'เวลา': 'Time',
  'ครบกำหนด': 'Due',
  'ชุด': 'set',
  'วัน': 'day(s)',
  'ลายเซ็น': 'Signature',
  'ไฟล์แนบ': 'Attachments',
  'ความเห็น': 'Comments',
  'ประวัติ': 'History',
  'ผู้ใช้': 'User',
  'ผู้ดูแลระบบ': 'Administrator',
  'ผู้บริหาร': 'Executive',
  'เจ้าหน้าที่ HR': 'HR officer',

  // ── สถานะที่ใช้ร่วมกัน ─────────────────────────────────────────────────
  'ฉบับร่าง': 'Draft',
  'รออนุมัติ': 'Awaiting approval',
  'อนุมัติแล้ว': 'Approved',
  'ไม่อนุมัติ': 'Not approved',
  'อนุมัติ': 'Approve',
  'ยกเลิกแล้ว': 'Cancelled',
  'ส่งกลับแก้ไข': 'Returned for revision',
  'ใช้งาน': 'Active',
  'ปิดใช้งาน': 'Disable',
  'ยังไม่เผยแพร่': 'Not published',
  'ปักหมุด': 'Pin',
  'เอาหมุดออก': 'Unpin',

  // ── หน้าแรก (Portal) ───────────────────────────────────────────────────
  'ระบบงานภายใน': 'Internal systems',
  'แอปพลิเคชัน': 'Applications',
  'รายการ': 'items',
  'ช่วยเหลือ': 'Help',
  'ช่วยเหลือ / แจ้งปัญหา': 'Help / report a problem',
  'เร็วๆ นี้': 'Coming soon',
  'เปิดใช้งาน': 'Open',
  'ระบบออนไลน์': 'System online',
  'สลับบัญชี': 'Switch account',
  'ออกจากระบบ': 'Sign out',
  'ปฏิทินวันหยุด': 'Holiday calendar',
  'วันหยุด': 'Holiday',
  'เสาร์-อาทิตย์': 'Weekend',
  'วันนี้': 'Today',
  'วันหยุดถัดไป': 'Next holiday',
  'อีก': 'in',
  'ค้นหาแอปพลิเคชัน…': 'Search applications…',
  'สวัสดีตอนเช้า': 'Good morning',
  'สวัสดีตอนบ่าย': 'Good afternoon',
  'สวัสดีตอนเย็น': 'Good evening',
  'กลับสู่หน้า Portal': 'Back to the portal',
  'สำหรับใช้งานภายในเท่านั้น': 'Internal use only',

  // ── ชื่อโมดูลบนหน้าแรก ─────────────────────────────────────────────────
  'บันทึก & อนุมัติ (E-Memo)': 'Memos & Approvals (E-Memo)',
  'บันทึก & อนุมัติ': 'Memos & Approvals',
  'จัดทำหนังสือ ออกเลขอัตโนมัติ และอนุมัติออนไลน์พร้อมลายเซ็น':
    'Draft letters, number them automatically, and approve online with a signature',
  'บันทึกงานฝ่ายบุคคล': 'HR Work Log',
  'บันทึกงานที่พนักงานแต่ละคนทำในแต่ละวัน แยกตามไซต์งาน':
    'What each person worked on each day, by site',
  'วงเงินสินเชื่อโครงการ': 'Project Credit Facilities',
  'ติดตามวงเงิน การเบิกใช้ คำขออนุมัติ และแผนกระแสเงินสด':
    'Track limits, drawdowns, approval requests and the cash plan',
  'รับพนักงานใหม่': 'Onboarding',
  'คลังข้อมูล แผน 30-60-90 วัน และแบบประเมินทดลองงาน':
    'Reference material, the 30-60-90 day plan, and the probation review',
  'ตั้งค่า': 'Settings',
  'ผู้ใช้และสิทธิ์ · โครงการ/หัวจดหมาย · ประเภทเอกสาร · โปรไฟล์และลายเซ็นของฉัน':
    'Users and permissions · Projects/letterhead · Document types · My profile and signature',
  'คู่มือปฏิบัติงาน (SOP)': 'Operating Manual (SOP)',
  'ระเบียบปฏิบัติมาตรฐาน ERP — กรณีศึกษา ผังกระบวนการ และเมนูรายงาน':
    'ERP standard operating procedures — case studies, process flows, and the report menu',
  'รายงานการประชุม': 'Meeting Minutes',
  'บันทึกการประชุมแยกตามโครงการ เก็บทุกเวอร์ชัน ไฟล์แนบ และความเห็นของทีม':
    'Minutes by project, every version kept, with attachments and team comments',
  'แผนผังระบบ (System Map)': 'System Map',
  'แผนผังระบบ': 'System Map',
  'กระบวนการทำงานของกลุ่ม ทะเบียนฟังก์ชันรายแผนก และจุดที่ใช้ AI ช่วยได้':
    'How the group works, the function register by department, and where AI can help',

  // ── เข้าสู่ระบบ ────────────────────────────────────────────────────────
  'ลงชื่อเข้าใช้ด้วย Google': 'Sign in with Google',
  'เข้าสู่ระบบด้วยอีเมล': 'Sign in with email',
  'รหัสผ่าน': 'Password',
  'หรือ': 'or',
  'บัญชีที่ผู้ดูแลระบบสร้างให้ (อีเมล + รหัสผ่าน)': 'An account your administrator created (email + password)',
  'ลืมรหัสผ่าน? ติดต่อผู้ดูแลระบบเพื่อขอรหัสผ่านใหม่':
    'Forgotten your password? Ask your administrator to reset it',

  // ── หน้าที่ไม่พบ / ข้อผิดพลาด ──────────────────────────────────────────
  'ไม่พบหน้านี้ (404)': 'Page not found (404)',
  'ลิงก์อาจไม่ถูกต้องหรือถูกย้ายไปแล้ว': 'The link may be wrong, or the page has moved',
  'กลับหน้าหลัก': 'Back to home',
  'เกิดข้อผิดพลาด': 'Something went wrong',
  'โมดูลนี้ยังไม่เปิดให้ใช้งาน': 'This module is not switched on yet',
  'ไม่มีสิทธิ์เข้าถึงหน้านี้': 'You do not have access to this page',

  // ── ส่วนที่ใช้ร่วมกัน: ช่วยเหลือ ปฏิทิน ข้อผิดพลาด ───────────────────────
  'เกิดข้อผิดพลาดบางอย่าง': 'Something went wrong',
  'ระบบพบข้อผิดพลาดที่ไม่คาดคิด กรุณาโหลดหน้าใหม่อีกครั้ง หากยังพบปัญหา โปรดติดต่อผู้ดูแลระบบ':
    'The system hit an unexpected error. Please reload the page, and contact your administrator if it keeps happening.',
  'โหลดหน้าใหม่': 'Reload page',
  'ลองใหม่อีกครั้ง': 'Try again',
  'กรุณากรอกข้อความ': 'Please enter a message',
  'ส่งเรื่องถึงผู้ดูแลระบบแล้ว ขอบคุณครับ': 'Sent to your administrator. Thank you.',
  'ส่งเรื่อง': 'Send',
  'พบปัญหาการใช้งานหรือมีข้อสงสัย ส่งข้อความถึงผู้ดูแลระบบได้ที่นี่':
    'Run into a problem or have a question? Send your administrator a message here.',
  'ส่วนที่เกี่ยวข้อง': 'Related to',
  '— เลือกส่วนที่เกี่ยวข้อง —': '— Choose an area —',
  'อื่น ๆ': 'Other',
  'รายละเอียด': 'Details',
  'อธิบายปัญหาหรือข้อสงสัย…': 'Describe the problem or question…',
  'เดือนก่อนหน้า': 'Previous month',
  'เดือนถัดไป': 'Next month',
  'วันหยุดถัดไป:': 'Next holiday:',
  'ภาพรวม': 'Overview',
  'ทะเบียนเอกสาร': 'Document register',
  'เมนูผู้ใช้': 'Account menu',
  'โปรไฟล์และลายเซ็น': 'Profile and signature',
  'ออกจากระบบแล้วเข้าด้วยบัญชีอื่น โดยกลับมาที่หน้านี้':
    'Sign out and back in as someone else, returning to this page',
  'เซ็นลายเซ็นในกรอบ (ใช้เมาส์หรือนิ้ว)': 'Sign inside the box (mouse or finger)',
  'ล้าง': 'Clear',

  // ── ภาพรวม E-Memo (แดชบอร์ด) ────────────────────────────────────────────
  'ช่วงเวลา:': 'Period:',
  'โครงการ:': 'Project:',
  'กำลังเตรียมไฟล์…': 'Preparing the file…',
  'ดาวน์โหลด Excel': 'Download Excel',
  'ตัวเลขทุกตัวกดเพื่อดูรายการจริงได้ · ข้อมูลตามตัวกรองด้านบน':
    'Every figure opens the documents behind it · filtered as set above',
  'อัปเดต:': 'Updated:',
  'โหลดภาพรวมไม่สำเร็จ:': 'Could not load the overview:',
  'กำลังโหลดภาพรวม…': 'Loading the overview…',
  'เอกสารทั้งหมด': 'All documents',
  'รับเข้าเดือนนี้': 'Received this month',
  'ค้างเกิน 14 วัน': 'Waiting over 14 days',
  'แนวโน้มจำนวนเอกสาร 12 เดือน': 'Documents over the last 12 months',
  'แนวโน้มจำนวนเอกสารรายเดือน': 'Documents per month',
  'ยังไม่มีข้อมูลพอจะแสดงแนวโน้ม': 'Not enough data to show a trend yet',
  'ไม่มีข้อมูลในช่วงที่เลือก': 'No data in the selected period',
  'กดที่เดือนเพื่อดูเอกสารของเดือนนั้น': 'Click a month to see its documents',
  'เอกสารรออนุมัติ ค้างมานานแค่ไหน': 'How long documents have been waiting',
  'นับจากวันที่รับเอกสาร': 'Counted from the date received',
  'มี': 'There are',
  'ฉบับค้างเกิน 14 วัน — ควรตามผู้อนุมัติที่ค้างอยู่':
    'documents waiting over 14 days — worth chasing the approver they sit with',
  'เวลาพิจารณาเฉลี่ย รายผู้อนุมัติ': 'Average time to decide, by approver',
  'นับจากที่ถึงคิวของแต่ละคน': 'Counted from when it reached each person',
  'ยังไม่มีการอนุมัติในช่วงที่เลือก': 'No approvals in the selected period',
  'สถานะเอกสาร': 'Document status',
  'เอกสารแยกตามโครงการ': 'Documents by project',
  'เอกสารล่าสุด': 'Latest documents',
  'ดูทั้งหมด': 'See all',
  'ยังไม่มีเอกสาร': 'No documents yet',
  'รออนุมัตินานที่สุด': 'Waiting longest',
  'ไม่มีเอกสารรออนุมัติ': 'Nothing waiting for approval',
  'ค้าง': 'waiting',

  // ── วงเงินสินเชื่อโครงการ ───────────────────────────────────────────────
  'บริหารวงเงินสินเชื่อโครงการ': 'Project credit facilities',
  'วงเงินสินเชื่อ (วงเงินกู้ระยะยาว)': 'Credit facilities (long-term)',
  'วงเงินสินเชื่อ (วงเงินหมุนเวียน)': 'Credit facilities (revolving)',
  'ครบกำหนด — เดือนนี้': 'Due — this month',
  'ครบกำหนด — เดือนหน้า': 'Due — next month',
  'สถานะคำขอ': 'Request status',
  'อยู่ระหว่างเสนออนุมัติ': 'Awaiting approval',
  'อนุมัติแล้ว (คำขอ)': 'Approved (requests)',
  'ประเภทวงเงิน': 'Facility type',
  'บริษัท': 'Company',
  'ธนาคาร': 'Bank',
  'เลขที่วงเงิน': 'Facility number',
  'อัตราดอกเบี้ย (%/ปี)': 'Interest rate (% per year)',
  'วงเงินที่อนุมัติ': 'Approved limit',
  'ยอดใช้ไปเริ่มต้น (baseline)': 'Opening drawn amount (baseline)',
  'วันครบกำหนด': 'Due date',
  'จำนวนเงิน': 'Amount',
  'วันเริ่ม': 'Start date',
  'อ้างอิง / หมายเหตุ': 'Reference / note',
  'เลขที่เอกสาร / อ้างอิง': 'Document number / reference',
  'ทุกประเภท': 'All types',
  'ค้นหา ธนาคาร / เลขที่วงเงิน': 'Search bank or facility number',
  'เพิ่มวงเงิน': 'Add facility',
  'วงเงิน': 'Limit',
  'ใช้ไป': 'Drawn',
  'การใช้': 'Utilisation',
  'ยังไม่มีวงเงินสินเชื่อ': 'No credit facilities yet',
  'เบิกใช้': 'Draw down',
  'อ้างอิง': 'Reference',
  'ยังไม่มีรายการสินเชื่อ': 'No credit entries yet',
  'ชำระแล้ว': 'Settled',
  'คำขอใช้วงเงิน': 'Facility requests',
  'ยื่นคำขอใหม่': 'New request',
  'เลือกวงเงิน': 'Choose a facility',
  '(เหลือ': '(available',
  'ยื่นคำขอ': 'Submit request',
  'ยังไม่มีคำขอ': 'No requests yet',
  'เดือน': 'Month',
  'งวด': 'Period',
  'รายรับ': 'Income',
  'ตั๋ว P/N ใหม่': 'New P/N notes',
  'รายการหัก': 'Deductions',
  'คงเหลือใช้ได้': 'Available',
  'รายละเอียดรายรับ': 'Income breakdown',
  'ลบงวดแผนเงินสด': 'Delete cash plan period',
  'ต้องการลบงวดนี้หรือไม่?': 'Delete this period?',
  'เพิ่มงวด': 'Add period',
  'เดือน/งวด': 'Month / period',
  'P/N ใหม่': 'New P/N',
  'หัก': 'Deducted',
  'คงเหลือ': 'Remaining',
  'ยังไม่มีแผนกระแสเงินสด': 'No cash plan yet',
  '· งวด': '· period',
  'ใช้ไปแล้ว': 'Drawn',
  '% · วงเงิน': '% · limit',

  // ── บันทึกงานฝ่ายบุคคล: ไซต์งาน พนักงาน ตารางรายวัน ──────────────────────
  'ยังไม่มีไซต์งานในขอบเขตของคุณ': 'No sites in your scope yet',
  'พนักงาน': 'Employees',
  'เริ่มบันทึก': 'Start recording',
  'ปฏิบัติการ ·': 'Operations ·',
  'สนับสนุน': 'Support',
  'เปิดบันทึก': 'Open log',
  'กรุณากรอกชื่อพนักงาน': 'Please enter the employee name',
  'เพิ่มพนักงานแล้ว': 'Employee added',
  'เปลี่ยนประเภทพนักงานแล้ว': 'Employee type changed',
  'ปิดใช้งานพนักงาน': 'Deactivate employee',
  'ปิดใช้งานพนักงานแล้ว': 'Employee deactivated',
  'รหัส (ถ้ามี)': 'Code (optional)',
  'สายปฏิบัติการ': 'Operations',
  'สายสนับสนุน': 'Support',
  'ยังไม่มีพนักงานในไซต์นี้ — เพิ่มด้านบนได้เลย': 'No employees at this site yet — add one above',
  'สลับประเภท': 'Switch type',
  'กำลังโหลดข้อมูลไซต์งาน…': 'Loading site data…',
  'เลือกไซต์งานด้านบนเพื่อเริ่มบันทึก': 'Pick a site above to start recording',
  'จัดการพนักงาน': 'Manage employees',
  '· โหมดดูอย่างเดียว': '· read-only',
  'ยังไม่มีพนักงานในไซต์นี้': 'No employees at this site yet',
  'เพิ่มพนักงาน': 'Add employee',
  'พนักงาน (': 'Employees (',
  'คลิกเซลล์เพื่อกระโดดไปแก้พนักงาน/วันนั้นในมุมมองสัปดาห์':
    'Click a cell to jump to that person and day in the weekly view',
  'คลิกช่องเพื่อเลือกกิจกรรม → หมวดต้นทุน · เซลล์ที่เกิน':
    'Click a cell to pick an activity → cost category · cells past',
  'วันจะล็อกอัตโนมัติ': 'days lock automatically',
  'ลงบันทึกรายวัน': 'Daily log',
  'การลา': 'Leave',
  'ทะเบียนงาน': 'Work catalogue',
  'ส่งออกเป็น Excel': 'Export to Excel',
  'ส่งออก Excel': 'Export Excel',
  'เลือกไซต์งาน': 'Choose a site',
  'เลือกกิจกรรม': 'Choose an activity',
  'เลือกหมวดต้นทุน · งาน:': 'Choose a cost category · activity:',
  'ไม่พบรายการ "': 'Nothing found for "',
  'จำนวนวันต้องอยู่ระหว่าง 0–60': 'The number of days must be between 0 and 60',
  'บันทึกจำนวนวันล็อกแล้ว': 'Lock window saved',
  'การแสดงผล': 'Display',
  'แสดงในตารางสัปดาห์เป็น': 'Show in the weekly grid as',
  'ล็อกการแก้ไขย้อนหลัง (ต่อไซต์)': 'Lock back-dated edits (per site)',
  'จำนวนวันที่ยังแก้ไขข้อมูลย้อนหลังได้ · เกินกว่านี้จะล็อกอัตโนมัติ (ผู้ดูแลระบบปลดล็อกได้)':
    'How many days back the log stays editable · beyond that it locks automatically (an administrator can unlock it)',
  'ซ่อนไซต์บนแดชบอร์ด': 'Hide sites on the dashboard',
  'ติ๊กเพื่อซ่อนการ์ดไซต์นั้นในหน้าภาพรวม (เฉพาะเครื่องนี้)':
    'Tick to hide that site card on the overview (this device only)',
  'รหัส *': 'Code *',
  'เช่น A-1': 'e.g. A-1',
  'หมวดหมู่ *': 'Category *',
  'A · งานสำนักงาน': 'A · Office work',
  'ชื่อกิจกรรม *': 'Activity name *',
  'การจับคู่หมวดต้นทุน': 'Cost-category mapping',
  'เลือกหมวดต้นทุนเอง (2 ขั้นตอน)': 'Pick the cost category by hand (two steps)',
  'กำหนดหมวดต้นทุนอัตโนมัติ (ขั้นตอนเดียว)': 'Set the cost category automatically (one step)',
  'รหัสหมวดต้นทุนอัตโนมัติ': 'Automatic cost-category code',
  'เช่น 5': 'e.g. 5',
  'ชื่อ (ไทย) *': 'Name (Thai) *',
  'ชื่อ (อังกฤษ)': 'Name (English)',
  'กิจกรรม': 'Activities',
  'หมวดหมู่': 'Category',
  'การจับคู่': 'Mapping',
  'เลือกเอง': 'By hand',
  'ชื่อ (ไทย)': 'Name (Thai)',
  'บันทึกกิจกรรมแล้ว': 'Activity saved',
  'บันทึกหมวดต้นทุนแล้ว': 'Cost category saved',

  // ── การลาและใบลา ────────────────────────────────────────────────────────
  'บันทึกผู้อนุมัติแล้ว': 'Approvers saved',
  'ผู้อนุมัติการลา': 'Leave approvers',
  'เลือกหัวหน้าหนึ่งคน แล้วติ๊กว่าใครเป็นลูกน้อง — หัวหน้าจะเห็นเฉพาะคำขอลาของคนที่ติ๊กไว้ · พนักงานหนึ่งคนมีหัวหน้าได้มากกว่าหนึ่ง เผื่อหัวหน้าลาแล้วงานไม่ค้าง':
    'Pick one supervisor, then tick who reports to them — a supervisor sees only the leave requests of the people ticked here. One person may have more than one supervisor, so nothing stalls while a supervisor is away.',
  'ยังไม่มีพนักงานในระบบ — เพิ่มพนักงานในไซต์งานก่อน แล้วจึงกลับมาผูกหัวหน้า':
    'No employees yet — add them to a site first, then come back to assign supervisors',
  'ยังไม่มีหัวหน้า': 'No supervisor',
  'คน': 'people',
  '— คำขอลาของคนเหล่านี้จะไปที่ผู้ดูแลระบบแทน ซึ่งใช้งานได้ แต่ไม่ใช่สิ่งที่ตั้งใจไว้':
    '— their leave requests go to an administrator instead, which works but is not the intent',
  'หัวหน้า': 'Supervisor',
  '— เลือกผู้อนุมัติ —': '— Choose an approver —',
  'ค้นหาพนักงาน': 'Search employees',
  'ค้นหาชื่อพนักงานหรือไซต์งาน…': 'Search by employee or site…',
  'ไม่พบพนักงานที่ค้นหา': 'No matching employees',
  'วัน ·': 'days ·',
  '— ไม่ได้ระบุเหตุผล': '— no reason given',
  'ส่งคำขอลาแล้ว รอการอนุมัติ': 'Leave request sent, awaiting approval',
  'ยกเลิกคำขอลา': 'Cancel leave request',
  'ยกเลิกคำขอนี้?': 'Cancel this request?',
  'ยกเลิกคำขอ': 'Cancel request',
  'ยกเลิกคำขอแล้ว': 'Request cancelled',
  'กำลังโหลดคำขอลา…': 'Loading leave requests…',
  'คำขอของฉัน': 'My requests',
  'ประวัติการพิจารณา': 'Decision history',
  'ขอลาใหม่': 'New leave request',
  'ชื่อพนักงาน': 'Employee',
  '— เลือกพนักงาน —': '— Choose an employee —',
  'ประเภทการลา': 'Leave type',
  'วันที่เริ่มลา': 'First day',
  'วันที่สิ้นสุด': 'Last day',
  'เหตุผล (ถ้ามี)': 'Reason (optional)',
  'เช่น ไปโรงพยาบาล': 'e.g. hospital appointment',
  'รวม': 'Total',
  'เปิดใบลาเพื่อพิมพ์': 'Open the leave form to print',
  'ใบลา': 'Leave form',
  'คำขอของท่านจะถูกส่งไปยังหัวหน้าที่ผู้ดูแลระบบกำหนดไว้':
    'Your request goes to the supervisor your administrator assigned',

  // ── คู่มือปฏิบัติงาน (SOP) ───────────────────────────────────────────────
  'กำลังโหลดผังกระบวนการ…': 'Loading the process flow…',
  'ยังไม่มีผังกระบวนการในหมวดนี้': 'No process flow in this area yet',
  'เลือกผังกระบวนการ': 'Choose a process flow',
  'ลบรายการ': 'Delete item',
  'ลบรายการแล้ว': 'Item deleted',
  'ค้นหารายงาน': 'Search reports',
  'ค้นหาจากสิ่งที่อยากรู้ หรือชื่อรายงาน…': 'Search by what you need to know, or by report name…',
  'กำลังโหลดเมนูรายงาน…': 'Loading the report menu…',
  'ลำดับ': 'No.',
  'ต้องการทราบ': 'What you need to know',
  'เมนูรายงานในระบบ': 'Where to find it',
  'กรุณากรอกให้ครบ': 'Please fill in every required field',
  'ต้องการทราบอะไร *': 'What do you need to know? *',
  'เช่น ตรวจสอบยอดหนี้คงค้างในระบบ': 'e.g. check outstanding payables',
  'เมนูรายงานในระบบ *': 'Where to find it *',
  'เช่น AP -&gt; Report -&gt; 10.2.1 (AP Aging Report)': 'e.g. AP → Report → 10.2.1 (AP Aging Report)',
  'ลำดับที่': 'Position',
  'ต่อจากรายการสุดท้าย': 'after the last item',
  'กรุณากรอกชื่อกรณีศึกษา': 'Please enter a case name',
  'กรุณาเลือกหมวดงาน': 'Please choose an area',
  'หมวดงาน *': 'Area *',
  'ชื่อกรณีศึกษา (ไทย) *': 'Case name (Thai) *',
  'เช่น กรณีการทำใบลดยอด PO…': 'e.g. issuing a PO decrement…',
  'ชื่อภาษาอังกฤษ': 'English name',
  'เช่น PO Decrement': 'e.g. PO Decrement',
  'ปัญหา / สถานการณ์ (เมื่อไรจึงใช้)': 'Problem / situation (when this applies)',
  'ขั้นตอนการปฏิบัติ': 'Steps',
  'ติ๊ก “ย่อย” เพื่อให้เป็นข้อย่อย (»)': 'Tick "sub" to make a step a sub-step (»)',
  'อธิบายสิ่งที่ต้องทำ…': 'Describe what to do…',
  'ย่อย': 'Sub',
  'เลื่อนขึ้น': 'Move up',
  'เลื่อนลง': 'Move down',
  'ลบขั้นตอน': 'Delete step',
  '+ เพิ่มขั้นตอน': '+ Add step',
  'แสดงในหมวดอื่นด้วย': 'Also show in these areas',
  '(เลขที่ยังนับจากหมวดหลัก)': '(numbering still follows the main area)',
  'อ้างอิงคู่มือ': 'Manual reference',
  'เช่น ERP Manual 14.3.68 — บทที่ 4 (PO)': 'e.g. ERP Manual 14.3.68 — chapter 4 (PO)',
  'หมายเหตุ [!]': 'Note [!]',
  'ข้อควรระวังเพิ่มเติม': 'Anything else to watch for',
  'ลบกรณีศึกษา': 'Delete case',
  'ลบกรณีศึกษาแล้ว': 'Case deleted',
  'อยู่ตำแหน่งสุดขอบแล้ว': 'Already at the end',
  'ค้นหากรณีศึกษา': 'Search cases',
  'ค้นหาจากชื่อเรื่อง ปัญหา หรือขั้นตอน…': 'Search by title, problem, or step…',
  'เพิ่มกรณีศึกษา': 'Add case',
  'กำลังโหลดกรณีศึกษา…': 'Loading cases…',
  'กลับไปที่รายการ': 'Back to the list',
  'เลือกกรณีศึกษาทางซ้ายเพื่อดูรายละเอียด': 'Choose a case on the left to read it',
  'ปัญหา / สถานการณ์': 'Problem / situation',
  'แนวปฏิบัติ': 'What to do',
  'อ้างอิง:': 'Reference:',
  'คัดลอกลิงก์มาที่รายการนี้': 'Copy a link to this item',
  'กำลังโหลดคู่มือ…': 'Loading the manual…',
  'วัตถุประสงค์ · ขอบเขต · หมายเหตุ': 'Purpose · scope · notes',
  'ขอบเขต:': 'Scope:',
  'เลื่อนดูแนวนอนได้ · ย่อ/ขยายได้': 'Scrolls sideways · zooms in and out',
  'ย่อ': 'Zoom out',
  'ขยาย': 'Zoom in',
  'ขั้นที่': 'Step',
  'เริ่ม / จบ': 'Start / end',
  'ขั้นตอน': 'Step',
  'จุดตัดสินใจ': 'Decision',
  'อนุมัติ / ใช่': 'Approve / yes',
  'คำอธิบายขั้นตอน': 'Step description',

  // ── แผนผังระบบ ──────────────────────────────────────────────────────────
  'ผลกระทบ': 'Impact',
  'เรียงจากคุ้มที่สุด — ผลกระทบสูงและทำได้ง่ายมาก่อน':
    'Sorted by payoff — high impact and easy to do come first',
  'ค้นหาฟังก์ชัน': 'Search functions',
  'ค้นหารหัส ชื่องาน หรือหมายเหตุ…': 'Search by code, name, or note…',
  'เฉพาะที่ทำหน้างาน': 'On-site only',
  'เฉพาะที่ยังทำมือ': 'Still manual only',
  'เพิ่มฟังก์ชัน': 'Add function',
  'แสดง': 'Showing',
  'จาก': 'of',
  'งานที่ทำ': 'What it does',
  'อยู่ใน ERP': 'In the ERP',
  'โมดูล': 'Module',
  'ไม่พบรายการที่ตรงกับที่กรอง': 'Nothing matches this filter',
  'ทำที่หน้างาน': 'Done on site',
  'คนนอกเป็นผู้กรอก': 'Filled in by an outside party',
  'ยังไม่มีกล่องงานในเลนนี้': 'No steps in this lane yet',
  'ยังไม่ยืนยัน': 'Not confirmed',
  'สิ่งที่ทำในขั้นนี้': 'What happens at this step',
  'รับงานมาจาก (': 'Comes from (',
  '— เป็นจุดเริ่มต้น': '— this is where it starts',
  'ส่งงานต่อไปที่ (': 'Goes on to (',
  '— เป็นปลายทาง': '— this is the end',
  'กำลังโหลดแผนผัง…': 'Loading the map…',
  'เลน': 'lanes',
  'กล่องงาน': 'steps',
  'กดที่กล่องงานเพื่อดูรายละเอียดและเส้นทางที่เชื่อมกับกล่องนั้น — เส้นทั้ง':
    'Click a step to see its detail and the paths into and out of it — all',
  'เส้นถ้าวาดพร้อมกันจะอ่านไม่ออก จึงแสดงเฉพาะของกล่องที่เลือก':
    'paths drawn at once would be unreadable, so only the selected step\'s are shown',
  'ความหมายของเส้น:': 'What the lines mean:',
  'ทุกแผนก': 'All departments',

  // ── รายงานการประชุม ─────────────────────────────────────────────────────
  'ลิงก์ต้องขึ้นต้นด้วย http:// หรือ https://': 'A link must start with http:// or https://',
  'ต้องเป็นไฟล์ภาพ': 'That has to be an image file',
  'ไม่รองรับไฟล์ SVG': 'SVG files are not accepted',
  'บันทึกรายงานก่อน แล้วจึงแทรกรูปได้': 'Save the minutes first, then you can insert images',
  'ตัวหนา': 'Bold',
  'ตัวเอียง': 'Italic',
  'ขีดเส้นใต้': 'Underline',
  'หัวข้อย่อย': 'Heading',
  '• รายการ': '• List',
  'รายการมีเลข': 'Numbered list',
  '1. ลำดับ': '1. Numbered',
  'รายการติ๊กถูก': 'Checklist',
  '☐ ติ๊ก': '☐ Check',
  'แทรกตาราง': 'Insert table',
  'ตาราง': 'Table',
  'ใส่ลิงก์': 'Add link',
  'ลิงก์': 'Link',
  'ถอดลิงก์': 'Remove link',
  'เนื้อหารายงานการประชุม': 'Body of the minutes',
  'ลบความเห็น': 'Delete comment',
  'ลบความเห็นนี้?': 'Delete this comment?',
  'เปิดไฟล์บันทึกเสียง': 'Open the recording',
  'จัดเก็บเข้ากลุ่ม:': 'Filed under:',
  'ยังไม่ได้จัดเก็บ': 'Not filed yet',
  'เอาออกจากกลุ่มนี้': 'Remove from this group',
  '— เลือกกลุ่มปลายทาง —': '— Choose a group —',
  '+ จัดเก็บเข้ากลุ่ม': '+ File under a group',
  'บันทึกนี้อยู่ในกล่องรอจัดเก็บถาวร การจัดเก็บเป็นการเพิ่มที่ให้หาเจอ ไม่ได้ย้ายออกจากกล่อง':
    'This recording sits in the inbox. Filing it adds somewhere to find it; it does not move it out of the inbox.',
  'ยังไม่มีเนื้อหา': 'Nothing written yet',
  'ยังไม่มีความเห็น': 'No comments yet',
  'เขียนความเห็น': 'Add a comment',
  'เขียนความเห็น…': 'Write a comment…',
  'ประวัติการแก้ไข': 'Edit history',
  'ทุกครั้งที่แก้ ระบบเก็บของเดิมไว้พร้อมชื่อเรื่องและวันที่ ณ ขณะนั้น กดดูได้ว่าตอนนั้นเขียนไว้ว่าอย่างไร':
    'Every edit keeps the previous version, with the title and date as they were. Open one to read what it said at the time.',
  'เพิ่มรายงานแล้ว': 'Minutes added',
  'กลุ่ม': 'Group',
  'ย้ายกลุ่มไม่ได้หลังสร้างแล้ว': 'The group cannot be changed once created',
  'ชื่อเรื่อง': 'Title',
  'เช่น ประชุมความก้าวหน้าโครงการ ครั้งที่ 12': 'e.g. Project progress meeting no. 12',
  'วันที่ประชุม': 'Meeting date',
  'เช่น 09:00 – 11:00': 'e.g. 09:00 – 11:00',
  'ผู้เข้าประชุม': 'Attendees',
  'คั่นชื่อด้วยเครื่องหมายจุลภาค เช่น ทนงศักดิ์, ชวิน, สุรวัจน์':
    'Separate names with commas',
  'ลิงก์ไฟล์บันทึกเสียง (ถ้ามี)': 'Recording link (optional)',
  'ใส่ลิงก์บันทึกจาก Fathom หรือ Transkriptor ได้ · รับเฉพาะลิงก์ที่ขึ้นต้นด้วย https://':
    'A Fathom or Transkriptor link works here · only links starting with https:// are accepted',
  'เผยแพร่ให้ผู้อื่นเห็น': 'Publish for others to see',
  '— เอาติ๊กออกเพื่อเก็บเป็นฉบับร่างที่มีแต่ท่านเห็น':
    '— untick to keep it a draft only you can see',
  'เนื้อหา': 'Body',
  'พิมพ์เนื้อหาได้เลย · การแทรกรูปทำได้หลังบันทึกครั้งแรก เพราะรูปต้องผูกกับรายงานที่มีอยู่จริง':
    'Type away · images can be inserted after the first save, since an image has to belong to minutes that exist',
  'กำลังโหลดรายงานการประชุม…': 'Loading the minutes…',
  'ลบรายงานการประชุม': 'Delete minutes',
  'เพิ่มรายงาน': 'Add minutes',
  'บันทึกเสียงที่ยังไม่ได้จัดเก็บเข้ากลุ่ม': 'Recordings not yet filed',
  'ค้นหารายงานการประชุม': 'Search minutes',
  'ค้นหาชื่อเรื่อง มติ ผู้เข้าประชุม หรือข้อความในรายงาน…':
    'Search titles, resolutions, attendees, or the text…',
  'พบ': 'Found',
  'ฉบับ': 'items',
  'เลือกรายงานทางซ้ายเพื่ออ่าน': 'Choose minutes on the left to read them',

  // ── ตั้งค่า: ประกาศ บริษัท รหัสเอกสาร ประเภทเอกสาร ───────────────────────
  'กรุณากรอกหัวข้อ': 'Please enter a title',
  'หัวข้อ *': 'Title *',
  'เช่น ปิดปรับปรุงระบบ': 'e.g. system maintenance',
  'ระดับ': 'Level',
  'แสดงผล': 'Visible',
  'ลบประกาศ': 'Delete announcement',
  'เพิ่มประกาศ': 'Add announcement',
  'ยังไม่มีประกาศ — กด “เพิ่มประกาศ”': 'No announcements yet — press "Add announcement"',
  'หัวข้อ': 'Title',
  'สลับการแสดงผล': 'Show or hide',
  'บันทึกบริษัทแล้ว': 'Company saved',
  'ตั้งเป็นบริษัทหลักแล้ว': 'Set as the default company',
  'ลบบริษัท': 'Delete company',
  'ลบบริษัทแล้ว': 'Company deleted',
  'บริษัท/ตราสำหรับหัวจดหมาย — ผู้สร้างเอกสารจะเลือกได้ตอนสร้างบันทึกข้อความ โลโก้และหัวจดหมายจะเปลี่ยนตามบริษัทที่เลือก':
    'Companies and marks for the letterhead — whoever writes a memo picks one, and the logo and letterhead follow that choice.',
  'เพิ่มบริษัท': 'Add company',
  'ชื่อบริษัท (ไทย) *': 'Company name (Thai) *',
  'บริษัท ... จำกัด': 'Company name',
  'ชื่อบริษัท (อังกฤษ)': 'Company name (English)',
  'ที่อยู่': 'Address',
  'โทรศัพท์': 'Telephone',
  'โทรสาร': 'Fax',
  'ตั้งเป็นบริษัทหลัก (ค่าเริ่มต้นเมื่อสร้างเอกสาร)': 'Make this the default for new documents',
  'ยังไม่มีบริษัท — กด “เพิ่มบริษัท” เพื่อเริ่ม': 'No companies yet — press "Add company" to start',
  'ค่าเริ่มต้น': 'Default',
  'ตั้งเป็นค่าเริ่มต้น': 'Make default',
  'บันทึกสายอนุมัติแล้ว': 'Approval chain saved',
  'เพิ่มรหัสเอกสารแล้ว': 'Document code added',
  'บันทึกรหัสเอกสารแล้ว': 'Document code saved',
  'ลบรหัสเอกสาร': 'Delete document code',
  'ลบรหัส': 'Delete code',
  'ลบรหัสเอกสารแล้ว': 'Document code deleted',
  'จัดการรหัสเอกสาร — เพิ่ม / แก้ไข / ลบ และกำหนดสายอนุมัติประจำแต่ละรหัส เมื่อผู้ใช้เลือกรหัสตอนสร้างเอกสาร ระบบจะเติมผู้อนุมัติให้อัตโนมัติและล็อกไว้':
    'Manage document codes — add, edit, delete, and set the approval chain for each. When someone picks a code while writing, the approvers fill in automatically and lock.',
  'เพิ่มรหัสเอกสาร': 'Add document code',
  'เช่น 08': 'e.g. 08',
  'แผนก / ชื่อย่อ': 'Department / short name',
  'เช่น ฝ่ายการเงิน': 'e.g. Finance',
  'ตำแหน่งผู้รับ (เรียน) — ไม่บังคับ': 'Addressee title (To) — optional',
  'เช่น ผู้จัดการฝ่ายการเงิน': 'e.g. Finance Manager',
  'ยังไม่มีรหัสเอกสาร — กด “เพิ่มรหัสเอกสาร” เพื่อเริ่ม':
    'No document codes yet — press "Add document code" to start',
  'แก้รหัส': 'Edit code',
  'ตำแหน่งผู้รับ (เรียน)': 'Addressee title (To)',
  'ชื่อ (ไม่บังคับ)': 'Name (optional)',
  '+ เพิ่มผู้อนุมัติ': '+ Add approver',
  'เพิ่มประเภทเอกสารแล้ว': 'Document type added',
  'ลบประเภทเอกสาร': 'Delete document type',
  'ลบประเภทเอกสารแล้ว': 'Document type deleted',
  'ชื่อประเภทเอกสารใหม่': 'New document type name',
  '+ เพิ่ม': '+ Add',
  'ยังไม่มีประเภทเอกสาร — เพิ่มด้านบนได้เลย': 'No document types yet — add one above',

  // ── ตั้งค่า: โครงการและหัวจดหมาย ────────────────────────────────────────
  'รหัสโครงการ': 'Project code',
  'เช่น BT1': 'e.g. BT1',
  'อักษรนำหน้าเลขเอกสาร': 'Document-number prefix',
  'เช่น BT': 'e.g. BT',
  'ชื่อโครงการ': 'Project name',
  'สีประจำโครงการ': 'Project colour',
  'ตัวอย่าง:': 'Preview:',
  'หัวจดหมายของโครงการนี้': 'Letterhead for this project',
  'กำลังโหลดข้อมูล…': 'Loading…',
  'ชื่อบริษัท/หน่วยงานและข้อมูลนี้จะแสดงบนหนังสือของโครงการนี้ (แต่ละโครงการตั้งได้ต่างกัน)':
    'This company or unit name and its details appear on every letter for this project (each project can differ).',
  'หัวกระดาษเริ่มต้น (บริษัท / ตรา)': 'Default letterhead (company / mark)',
  '— ใช้ค่าเริ่มต้นของระบบ —': '— use the system default —',
  'เอกสารทุกใบของโครงการนี้จะใช้หัวกระดาษนี้โดยอัตโนมัติ (ผู้สร้างเอกสารเปลี่ยนได้หากจำเป็น)':
    'Every document in this project uses this letterhead automatically (the writer can change it if needed).',
  'ชื่อบริษัท / หน่วยงาน (ไทย)': 'Company / unit name (Thai)',
  'เช่น กิจการร่วมค้า ซีวีอี': 'e.g. CVE Joint Venture',
  'เทเล็กซ์': 'Telex',
  'ผู้จัดการโครงการ / ผู้ลงนาม': 'Project manager / signatory',
  'ชื่อผู้จัดการโครงการ': 'Project manager name',
  'ชื่อนี้จะไปอยู่ใต้ “ขอแสดงความนับถือ” ของทุกเอกสารในโครงการนี้':
    'This name goes under "Yours sincerely" on every document in this project',
  'ตำแหน่งผู้ลงนาม': 'Signatory title',
  'เช่น ผู้จัดการโครงการ': 'e.g. Project Manager',
  'ผู้จัดการโครงการ (บัญชีสำหรับอนุมัติ)': 'Project manager (approving account)',
  'เลือกบัญชีผู้ใช้ในระบบที่เป็นผู้จัดการโครงการ — เวลาสร้าง/ส่งอนุมัติเอกสารของโครงการนี้ ระบบจะส่งให้ท่านนี้อนุมัติโดยอัตโนมัติ (แก้เปลี่ยนได้ตอนส่ง)':
    'Choose the account that is this project\'s manager — documents sent for approval here go to them automatically (and can still be changed when sending).',
  '— ยังไม่กำหนด (เลือกผู้อนุมัติเองตอนส่ง) —': '— not set (choose approvers when sending) —',
  '(บัญชีถูกปิดใช้งาน)': '(account is deactivated)',
  'ลายเซ็นผู้ลงนาม (อัตโนมัติ)': 'Signatory signature (automatic)',
  'อัปโหลดรูปลายเซ็น (พื้นหลังโปร่งใส .png จะสวยที่สุด) — ระบบจะประทับลายเซ็นนี้ใต้ “ขอแสดงความนับถือ” ให้อัตโนมัติทุกเอกสาร ไม่ต้องรอเซ็นทีละใบ':
    'Upload a signature image (a transparent .png looks best) — it is stamped under "Yours sincerely" on every document automatically, with nothing to sign one by one.',
  'มีลายเซ็นแล้ว': 'Signature set',
  'ยังไม่มี': 'Not set',
  'ลบลายเซ็น': 'Remove signature',
  'บันทึกโครงการก่อน จึงจะอัปโหลดลายเซ็นได้': 'Save the project first, then you can upload a signature',
  'คำลงท้าย': 'Closing',
  'ขอแสดงความนับถือ': 'Yours sincerely',
  'ผู้รับเริ่มต้น (เรียน)': 'Default addressee (To)',
  'ปิดใช้งานโครงการ': 'Deactivate project',
  'เพิ่มโครงการ': 'Add project',
  'ชื่อ': 'Name',
  'อักษรนำหน้า': 'Prefix',
  'ผู้จัดการโครงการ (ผู้ลงนาม)': 'Project manager (signatory)',
  'ยังไม่มีโครงการ — กด “เพิ่มโครงการ” เพื่อเริ่ม': 'No projects yet — press "Add project" to start',
  'ตั้งลายเซ็นแล้ว': 'Signature set',
  'ยังไม่ได้ตั้งลายเซ็น': 'No signature set',
  'ยังไม่มีลายเซ็น': 'No signature',
  'ผูกอีเมลอนุมัติ': 'Approval account linked',
  'ยังไม่ผูกบัญชีสำหรับอนุมัติ': 'No approving account linked',
  'ยังไม่ผูกอีเมล': 'No email linked',
  'ยังไม่ได้ตั้ง': 'Not set',
  'บันทึกโครงการแล้ว': 'Project saved',

  // ── ตั้งค่า: ผู้ใช้ สิทธิ์ ลายเซ็น ──────────────────────────────────────
  'กำลังโหลดสิทธิ์…': 'Loading permissions…',
  'ผู้ดูแลระบบมีสิทธิ์ทุกอย่างโดยอัตโนมัติ — ไม่ต้องตั้งค่าสิทธิ์':
    'An administrator has every permission automatically — nothing to set here',
  'เปิดสวิตช์เพื่อให้สิทธิ์ · ปิดเพื่อห้าม · ค่าเริ่มต้นมาจาก':
    'Switch on to grant · off to deny · defaults come from the',
  'ของผู้ใช้ — รายการที่ปรับต่างจากบทบาทจะมีป้าย': 'role — anything changed from it is marked',
  'แก้เฉพาะคนนี้': 'set for this person',
  'การมองเห็นเอกสาร (E-Memo)': 'Document visibility (E-Memo)',
  'เลือกโครงการ/ประเภทที่ผู้ใช้คนนี้มองเห็นได้ —': 'Choose which projects and types this person can see —',
  '· ถ้าเลือกบางอัน จะเห็นเฉพาะเอกสารที่ตรงกับที่เลือกเท่านั้น':
    '· pick some and they see only the documents that match',
  '(ทุกโครงการ)': '(all projects)',
  '(ทุกประเภท)': '(all types)',
  'ล้าง (เห็นทุกเอกสาร)': 'Clear (see everything)',
  'การเปลี่ยนแปลงจะถูกบันทึกเมื่อกดปุ่มบันทึกด้านล่าง': 'Changes are saved when you press Save below',
  'ลายเซ็นต้องเป็นรูปภาพ': 'A signature has to be an image',
  'รูปลายเซ็นใหญ่เกิน 2 MB': 'The signature image is larger than 2 MB',
  'บันทึกลายเซ็นแล้ว': 'Signature saved',
  'ลบลายเซ็นแล้ว': 'Signature removed',
  'ลายเซ็นของผู้ใช้รายนี้': 'This person\'s signature',
  'ใช้พิมพ์บนหนังสือที่ผู้ใช้รายนี้อนุมัติ · การเปลี่ยนแปลงถูกบันทึกในประวัติระบบว่าผู้ดูแลคนใดเป็นผู้ตั้งให้':
    'Printed on the letters this person approves · the audit trail records which administrator set it',
  'เปลี่ยนรูป': 'Change image',
  'ต้องเป็นอีเมล Google (Gmail/Workspace) ที่จะใช้ Sign in with Google':
    'Must be the Google address (Gmail or Workspace) used to sign in with Google',
  'วิธีเข้าสู่ระบบ': 'Sign-in method',
  'ปิดใช้งานผู้ใช้': 'Deactivate user',
  'ลบผู้ใช้': 'Delete user',
  'ลบผู้ใช้แล้ว': 'User deleted',
  'เพิ่มผู้ใช้': 'Add user',
  'เข้าระบบด้วย': 'Signs in with',
  'สังกัดโครงการ': 'Projects',
  'ยังไม่มีผู้ใช้ — กด “เพิ่มผู้ใช้” เพื่อเริ่ม': 'No users yet — press "Add user" to start',
  'มีแล้ว': 'set',
  'บันทึกผู้ใช้แล้ว': 'User saved',

  // ── โปรไฟล์ของฉัน ───────────────────────────────────────────────────────
  'โหลดข้อมูลโปรไฟล์ไม่สำเร็จ:': 'Could not load your profile:',
  'ตำแหน่ง (แสดงใต้ชื่อในเอกสาร)': 'Job title (shown under your name on documents)',
  'เช่น ผู้จัดการฝ่ายวิศวกรรม': 'e.g. Engineering Manager',
  'ลายเซ็น (ไม่บังคับ)': 'Signature (optional)',
  'อัปโหลดรูปลายเซ็น — จะแสดงเหนือชื่อในหนังสือโดยอัตโนมัติ (PNG พื้นโปร่งใสจะดูดีที่สุด)':
    'Upload a signature image — it appears above your name automatically (a transparent PNG looks best)',
  'คลิกเพื่ออัปโหลดรูปลายเซ็น': 'Click to upload a signature image',
  'PNG/JPG · สูงสุด 2 MB': 'PNG or JPG · up to 2 MB',
  'บันทึกโปรไฟล์เรียบร้อยแล้ว': 'Profile saved',

  // ── แนะแนวพนักงานใหม่ (ยังไม่เปิดใช้งาน) ────────────────────────────────
  'กลับรายชื่อพนักงานใหม่': 'Back to new starters',
  'งาน': 'tasks',
  'ไม่มีรายการ': 'Nothing here',
  'แบบประเมินทดลองงาน': 'Probation review',
  'ผู้ประเมิน': 'Reviewer',
  'ผลการประเมิน': 'Outcome',
  '— ยังไม่สรุป —': '— not decided —',
  'ผ่านทดลองงาน': 'Passed probation',
  'ขยายเวลาทดลองงาน': 'Probation extended',
  'ไม่ผ่าน': 'Did not pass',
  'คะแนนรายด้าน (1–5)': 'Scores by area (1–5)',
  'จุดเด่น': 'Strengths',
  'สิ่งที่ควรพัฒนา': 'To work on',
  'ผลล่าสุด:': 'Latest outcome:',
  'เพิ่มพนักงานใหม่': 'Add a new starter',
  'วันเริ่มงาน': 'Start date',
  'เบอร์โทร': 'Phone',
  'แผนงาน 30-60-90 วันจะถูกสร้างจากเทมเพลตที่ใช้งานอยู่ให้อัตโนมัติ':
    'The 30-60-90 day plan is created automatically from the active template',
  'ยังไม่มีพนักงานใหม่ในระบบติดตาม': 'No new starters being tracked yet',
  'ความคืบหน้า': 'Progress',
  'เริ่มงาน': 'Started',
  'แนะแนวและติดตามพนักงานใหม่ 90 วัน': 'Onboarding and 90-day follow-up',
  'เทมเพลตงานในแต่ละช่วง — เมื่อเพิ่มพนักงานใหม่ ระบบจะคัดลอกรายการเหล่านี้เป็นแผนติดตามให้อัตโนมัติ':
    'Task templates per stage — adding a new starter copies these into their plan automatically',
  'ยังไม่มีรายการ': 'Nothing here yet',
  'เพิ่มงาน…': 'Add task…',
  'เพิ่มข้อมูลพนักงานใหม่': 'Add a resource',
  'หมวด': 'Category',
  'ต้องลงนาม': 'Signature required',
  'ลิงก์ภายนอก (ถ้ามี)': 'External link (optional)',
  'แนบไฟล์ (ถ้ามี)': 'Attach a file (optional)',
  'เพิ่มข้อมูล': 'Add resource',
  'ยังไม่มีข้อมูลในคลัง': 'Nothing in the library yet',
  'เปิดไฟล์': 'Open file',

  // ── เข้าสู่ระบบ ─────────────────────────────────────────────────────────
  'ระบบงานภายใน · วิจิตรภัณฑ์ก่อสร้าง': 'Internal systems · Vichitbhan Construction',
  'กรุณาเข้าสู่ระบบด้วยบัญชี': 'Please sign in with the account',
  'เสร็จแล้วระบบจะพากลับไปที่เอกสารเดิมให้เอง': 'You will be taken back to the document afterwards',
  'เข้าสู่ระบบด้วยบัญชีของท่าน เพื่อเปิดดูเอกสารที่ส่งถึงท่าน':
    'Sign in with your account to open the document sent to you',
  'กำลังเข้าสู่ระบบด้วย Google…': 'Signing in with Google…',

  // ── E-Memo: เขียนบันทึกข้อความ ──────────────────────────────────────────
  'ออกโดยไม่บันทึก?': 'Leave without saving?',
  'ข้อมูลที่กรอกไว้จะหายไป ต้องการออกจากหน้านี้หรือไม่?': 'What you have typed will be lost. Leave this page?',
  'ออกโดยไม่บันทึก': 'Leave without saving',
  'บริษัท / ตราหัวจดหมาย': 'Company / letterhead mark',
  'หัวกระดาษที่บันทึกไว้ (บริษัทถูกปิดใช้งาน)': 'Saved letterhead (company deactivated)',
  'ค่าเริ่มต้นของโครงการนี้ถูกเลือกให้แล้ว — เปลี่ยนได้หากต้องการ':
    'This project\'s default is already selected — change it if you need to',
  '— เลือกโครงการ —': '— Choose a project —',
  'รหัสเอกสาร': 'Document code',
  '— เลือกรหัส —': '— Choose a code —',
  'เลขที่เอกสาร (อัตโนมัติ):': 'Document number (automatic):',
  'กำลังคำนวณ…': 'Working it out…',
  'เลือกโครงการและรหัสเอกสารเพื่อดูเลขที่': 'Choose a project and a code to see the number',
  'ประเภทเอกสาร': 'Document type',
  '— ไม่ระบุ —': '— none —',
  'วันที่เอกสาร': 'Document date',
  'เรื่อง': 'Subject',
  'เช่น ขออนุมัติ…': 'e.g. request for approval…',
  'เรียน (ผู้รับ)': 'To (addressee)',
  'อ้างถึง (ไม่บังคับ)': 'Reference (optional)',
  'เลือกจากเอกสารที่มีอยู่ในระบบ (กดแล้วลิงก์ไปเอกสารตัวจริงได้) · เอกสารอื่นที่ไม่มีในระบบให้แนบเป็นไฟล์แทน':
    'Pick a document already in the system, and the reference becomes a link to it · anything not in the system should be attached as a file instead',
  'สำเนาเรียน / CC (ไม่บังคับ)': 'Copy to / CC (optional)',
  'สิ่งที่ส่งมาด้วย (ไม่บังคับ)': 'Enclosures (optional)',
  'เช่น สรุปปริมาณ': 'e.g. quantity summary',
  'จำนวน': 'Quantity',
  'หน่วย': 'Unit',
  'หน่วย เช่น ชุด/แผ่น/เล่ม/ฉบับ': 'Unit — set, sheet, volume, copy',
  '+ เพิ่มรายการ': '+ Add item',
  'เนื้อความ': 'Body',
  'รายละเอียดเนื้อความ (จะแสดงในหนังสือฝั่งขวา)': 'The body of the letter (it appears in the preview on the right)',
  'แนบไฟล์เพิ่มเติม (ไม่บังคับ)': 'Additional attachments (optional)',
  'เอกสารประกอบ — แนบได้หลายไฟล์ เพิ่มเติมจากตัวหนังสือ ไม่ได้แทนที่กัน':
    'Supporting documents — attach as many as you need; they sit alongside the letter, not in place of it',
  'กำลังคัดลอกไฟล์แนบจากใบเดิม…': 'Copying the attachments from the original…',
  'เสร็จ': 'Done',
  'กำลังบีบรูปเพื่อลดขนาด…': 'Compressing images…',
  'รูปภาพจะถูกบีบอัตโนมัติ · PDF และรูปภาพจะรวมเข้ากับหนังสือ · Word/Excel แนบเป็นไฟล์ประกอบ · สูงสุด 200 MB/ไฟล์':
    'Images are compressed automatically · PDFs and images are merged into the letter · Word and Excel stay separate attachments · up to 200 MB per file',
  'ผู้จัดการโครงการ / ผู้ลงนาม (อนุมัติลำดับแรก)': 'Project manager / signatory (approves first)',
  'อนุมัติเป็นลำดับแรก': 'approves first',
  'ก่อนส่งต่อผู้อนุมัติที่สูงกว่า · ผู้จัดทำ': 'before it goes to more senior approvers · the writer',
  'เป็นผู้ร่าง': 'drafted it',
  'กำหนดจากโครงการ': 'set by the project',
  '— เลือกผู้จัดการโครงการ (ผู้ลงนาม) —': '— Choose the project manager (signatory) —',
  'โครงการนี้ยังไม่ได้ตั้งผู้จัดการโครงการถาวร — เลือกผู้ลงนามสำหรับเอกสารนี้ (ตั้งถาวรได้ที่ ตั้งค่า E-Memo → โครงการ)':
    'This project has no standing project manager — choose a signatory for this document (you can set a permanent one under E-Memo settings → Projects)',
  'เลือกโครงการก่อน': 'Choose a project first',
  'กำหนดจากรหัสเอกสาร': 'set by the document code',
  'ผู้อนุมัติลำดับที่ 1 คือ': 'The first approver is',
  'ท่านเป็นผู้ลงนามของเอกสารนี้เอง ถ้าไม่เลือกผู้อนุมัติที่สูงกว่า จะไม่มีผู้ใดตรวจสอบเอกสารเลย — เลือกอย่างน้อย 1 คน หรือกด “บันทึกเป็นฉบับร่าง”':
    'You are the signatory on this document yourself. With no more senior approver, nobody reviews it — choose at least one person, or press "Save as draft".',
  'ยังไม่มีบัญชีผู้อนุมัติในระบบ — ติดต่อผู้ดูแลระบบให้เพิ่มผู้ใช้ก่อน หรือเว้นว่างไว้เพื่อบันทึกเป็น':
    'There are no approver accounts yet — ask an administrator to add users, or leave this empty and save as a',
  'แล้วส่งอนุมัติภายหลังได้': 'and send it for approval later',
  'เปิดเอกสารที่บันทึกไว้เพื่อดำเนินการต่อ →': 'Open the saved document to carry on →',
  'ถัดไป →': 'Next →',
  'บันทึกเป็นฉบับร่าง': 'Save as draft',
  'ตัวอย่างหนังสือ': 'Letter preview',
  'บันทึกข้อความขออนุมัติ': 'Memorandum requesting approval',

  // ── E-Memo: หน้าเอกสารและการพิจารณา ─────────────────────────────────────
  'บันทึกการ': 'Recording the',
  'เรียบร้อย': 'is done',
  'สถานะเอกสารปัจจุบัน:': 'Current status:',
  'ไปที่หน้ารายการเอกสาร E-Memo': 'Go to the E-Memo register',
  'กำลังนำท่านไปยังหน้ารายการใน': 'Taking you to the register in',
  'วินาที…': 'seconds…',
  'ส่งต่อเรียบร้อย': 'Forwarded',
  'ส่งคำขออนุมัติต่อไปยัง': 'The approval request has gone on to',
  'แล้ว': '',
  'เอกสาร': 'Document',
  'เรียน': 'To',
  '— มีเอกสารรอการพิจารณาอนุมัติจากท่าน': '— a document is waiting for your decision',
  'สิ่งที่ส่งมาด้วย': 'Enclosures',
  'กำลังเปิดเอกสาร…': 'Opening the document…',
  'เปิดดูหนังสือฉบับเต็ม (PDF)': 'Open the full letter (PDF)',
  'เอกสารนี้ยังไม่มีไฟล์ PDF (เป็นเอกสารที่สร้างก่อนระบบสร้างไฟล์อัตโนมัติ)':
    'This document has no PDF (it was created before the system generated them automatically)',
  'สายอนุมัติ': 'Approval chain',
  'ผู้อนุมัติ': 'Approver',
  'ลำดับ · ท่านคือลำดับที่': 'in the chain · you are number',
  'เอกสารแนบ': 'Attachments',
  'กำลังเปิด…': 'Opening…',
  'เปิดดู': 'Open',
  'ท่านต้องการดำเนินการอย่างไร?': 'What would you like to do?',
  'เห็นชอบและลงลายเซ็น': 'Approve and sign',
  'ให้ผู้จัดทำแก้ไขแล้วส่งใหม่ — ต้องระบุเหตุผล':
    'Send it back to the writer to amend and resubmit — a reason is required',
  'ปฏิเสธคำขอ — ต้องระบุเหตุผล': 'Refuse the request — a reason is required',
  'ส่งให้ผู้อื่นพิจารณา': 'Pass to someone else',
  'มอบหมายให้บุคคลอื่นพิจารณาในลำดับนี้แทนท่าน — ระบบจะส่งอีเมลลิงก์ให้':
    'Hand your place in the chain to someone else — they get an email with a link',
  'อีเมลผู้รับ *': 'Recipient email *',
  'ความเห็นเพิ่มเติม (ไม่บังคับ)': 'Additional comment (optional)',
  'เซ็นเอง': 'Sign here',
  'อัปโหลดรูป': 'Upload an image',
  'ลิงก์นี้หมดอายุ': 'This link has expired',
  '· ใช้สำหรับเอกสารฉบับนี้เท่านั้น': '· valid for this document only',
  'คุณยังไม่ได้ตั้งค่าลายเซ็น หากอนุมัติตอนนี้ เอกสารจะไม่มีรูปลายเซ็นของคุณ — แนะนำให้ตั้งค่าลายเซ็นที่หน้า “โปรไฟล์ของฉัน” ก่อน':
    'You have not set a signature. Approving now leaves the document without your signature image — it is worth setting one under "My profile" first.',
  'เอาออก': 'Remove',
  'พิมพ์ชื่อหรืออีเมลเพื่อค้นหา': 'Type a name or email to search',
  '+ เพิ่มผู้รับสำเนา': '+ Add a copy recipient',
  'ผู้รับสำเนาต้องมีบัญชีในระบบ · จะได้รับอีเมลแจ้ง เปิดดูเอกสารและร่วมแสดงความเห็นได้ในหน้าเดียวกับผู้อนุมัติ (ไม่ต้องอนุมัติ)':
    'Copy recipients need an account · they are emailed, and can read the document and comment on the same page as the approvers, without approving',
  'ขอความเห็น': 'Ask for an opinion',
  'ขอความเห็นประกอบการพิจารณาจากผู้ใช้ในระบบ — ระบบจะส่งอีเมลให้เข้ามาดูเอกสารและตอบในหน้านี้':
    'Ask someone in the system for an opinion before you decide — they are emailed and can reply on this page',
  'โดยไม่ต้องอนุมัติ': 'without approving',
  '(ท่านยังเป็นผู้ตัดสิน)': '(the decision stays yours)',
  'ขอความเห็นจาก': 'Ask',
  '— เลือกผู้ใช้ —': '— Choose someone —',
  'คำถาม / สิ่งที่ขอปรึกษา (ไม่บังคับ)': 'Question / what you are asking about (optional)',
  'เช่น รบกวนช่วยดูเรื่องราคาต่อหน่วยให้หน่อยครับ…': 'e.g. could you take a look at the unit price…',
  'ยกเลิกเอกสาร': 'Cancel document',
  'ยกเลิกเอกสารนี้?\nเอกสารจะไม่เดินในสายอนุมัติต่อ และกลับคืนไม่ได้':
    'Cancel this document?\nIt will stop moving through the approval chain, and this cannot be undone.',
  'ยกเลิกเอกสารแล้ว': 'Document cancelled',
  '← กลับทะเบียนเอกสาร': '← Back to the register',
  'กลับทะเบียนเอกสาร': 'Back to the register',
  'ระบบบันทึกผลการพิจารณาของคุณเรียบร้อยแล้ว': 'Your decision has been recorded',
  'คุณถูกขอความเห็นในเอกสารนี้': 'You have been asked for an opinion on this document',
  'ท่านไม่จำเป็นต้องอนุมัติ — เพียงอ่านเอกสารแล้วให้ความเห็นในช่องด้านล่าง':
    'You do not need to approve — just read the document and leave your view below',
  'ให้ความเห็น': 'Give an opinion',
  'ท่านกำลังใช้งานด้วยคนละบัญชีกับที่อีเมลส่งถึง': 'You are signed in as a different account from the one this email went to',
  'อีเมลฉบับนี้ส่งถึง': 'This email was sent to',
  'แต่เครื่องนี้เข้าสู่ระบบด้วย': 'but this device is signed in as',
  'สลับไปบัญชี': 'Switch to',
  'เข้าสู่ระบบเสร็จแล้วระบบจะพากลับมาที่เอกสารฉบับนี้ให้เอง': 'You will be brought back to this document once signed in',
  'เอกสารนี้รอการอนุมัติจากคุณ': 'This document is waiting for your approval',
  'ตรวจเอกสารด้านล่าง แล้วเลือกดำเนินการที่ปุ่มด้านบน': 'Read the document below, then choose an action above',
  'คุณยังไม่ได้ตั้งค่าลายเซ็น —': 'You have not set a signature —',
  'ตั้งค่าลายเซ็นที่โปรไฟล์': 'set one in your profile',
  'เพื่อให้ลายเซ็นปรากฏบนเอกสารที่อนุมัติ': 'so it appears on the documents you approve',
  'วันที่รับ': 'Received',
  'ดูตัวอย่างเอกสารที่อ้างถึง': 'Preview the referenced document',
  'สำเนาเรียน': 'Copy to',
  'อ้างถึง': 'Reference',
  'สอบถาม/ขอความเห็นจากผู้อื่นก่อนตัดสินใจ — ยังไม่ใช่การอนุมัติ':
    'Ask someone else before you decide — this is not an approval',
  'ไม่อนุมัติเอกสาร และส่งกลับให้ผู้จัดทำแก้ไขเพื่อยื่นใหม่ (ต้องระบุเหตุผล)':
    'Refuse the document and send it back to be amended and resubmitted (a reason is required)',
  'อนุมัติเอกสาร และส่งต่อผู้อนุมัติลำดับถัดไป (ถ้ามี)':
    'Approve the document and pass it to the next approver, if there is one',
  'แก้ไขเนื้อหาเอกสารก่อนส่งอนุมัติ': 'Edit the document before sending it for approval',
  'ส่งเอกสารเข้าสายอนุมัติ (ผู้จัดการโครงการอนุมัติเป็นลำดับแรก)':
    'Send the document into the approval chain (the project manager approves first)',
  'ส่งอนุมัติ': 'Send for approval',
  'ตรวจสอบ (QR)': 'Verify (QR)',
  'เปิดเต็มจอเพื่ออ่าน': 'Open full screen to read',
  'ดาวน์โหลดไฟล์ที่กำลังเปิด': 'Download the file you are viewing',
  'กำลังรวมไฟล์แนบเข้าเอกสาร… (จะแสดงอัตโนมัติเมื่อเสร็จ)':
    'Merging the attachments into the document… (it will appear when it is done)',
  'ไฟล์แนบอื่น ๆ (เปิด/ดาวน์โหลด)': 'Other attachments (open or download)',
  'กำลังเตรียม…': 'Preparing…',
  'ตำแหน่งจัดเก็บไฟล์': 'Where the file is stored',
  'ระบบจัดเก็บ:': 'Storage:',
  '(สำรองข้อมูลอัตโนมัติ)': '(backed up automatically)',
  'ยังไม่มีไฟล์หนังสือสำหรับเอกสารนี้': 'There is no letter file for this document yet',
  'บันทึกและการพิจารณา': 'Notes and decisions',
  'ให้ความเห็นของคุณที่นี่': 'Add your view here',
  'แจ้งเตือนถึง:': 'Notify:',
  '· จะได้รับอีเมลพร้อมลิงก์มาที่เอกสารนี้': '· they get an email with a link to this document',
  'ลบไฟล์': 'Delete file',
  'สร้างเอกสารแล้ว แต่ส่งอีเมลแจ้งผู้อนุมัติไม่สำเร็จ — กรุณาแจ้งผู้อนุมัติด้วยตนเอง':
    'The document was created, but the approver could not be emailed — please tell them yourself',
  'สร้างเอกสารจากใบเดิมแล้ว': 'Created from the existing document',
  'ส่งเข้าสายอนุมัติแล้ว แต่ส่งอีเมลแจ้งผู้อนุมัติไม่สำเร็จ — กรุณาแจ้งผู้อนุมัติด้วยตนเอง':
    'It is in the approval chain, but the approver could not be emailed — please tell them yourself',
  'ส่งเข้าสายอนุมัติแล้ว': 'Sent into the approval chain',
  'บันทึกการแก้ไขแล้ว': 'Changes saved',
  'ยังไม่มีการพิจารณาหรือข้อความ — เริ่มการสนทนาด้านล่างได้เลย':
    'No decisions or messages yet — start the conversation below',
  'โดย': 'by',
  'ผู้จัดการโครงการ': 'Project manager',
  'ลงลายเซ็นบนเอกสารแล้ว': 'Signed the document',
  'เปิดดูเอกสาร:': 'Open the document:',

  // ── E-Memo: ทะเบียนหนังสือ ──────────────────────────────────────────────
  'ตั้งค่า E-Memo (โครงการ / รหัส / สายอนุมัติ)': 'E-Memo settings (projects / codes / approval chains)',
  'ตั้งค่า E-Memo': 'E-Memo settings',
  'เพิ่มเอกสาร': 'New document',
  'ค้นหาเลขที่ / เรื่อง / รหัสเอกสาร': 'Search by number, subject, or code',
  'ทุกประเภทเอกสาร': 'All document types',
  'เอกสารของฉัน': 'My documents',
  'เฉพาะเอกสารที่ฉันเป็นผู้สร้าง': 'Only the documents I created',
  'ที่ฉันเคยดำเนินการ': 'I have acted on',
  'เอกสารที่ฉันเคยอนุมัติ ไม่อนุมัติ หรือให้ความเห็น — เรียงจากที่ทำล่าสุด':
    'Documents I approved, refused, or commented on — most recent first',
  'ล้างตัวกรองทั้งหมด': 'Clear all filters',
  'วันที่รับ (ค.ศ.):': 'Received (AD):',
  'วันที่รับ ตั้งแต่': 'Received from',
  'วันที่รับ ถึง': 'Received to',
  '7 วันล่าสุด': 'Last 7 days',
  '30 วันล่าสุด': 'Last 30 days',
  'เดือนก่อน': 'Last month',
  'ล้างวันที่': 'Clear dates',
  'ยังไม่มีเอกสารในระบบ — เริ่มสร้างเอกสารฉบับแรกได้เลย': 'No documents yet — create the first one',
  'รออนุมัติจากคุณ': 'Waiting for you',
  'เซิร์ฟเวอร์กำลังเริ่มทำงาน (โหมดประหยัดพลังงาน) — การโหลดครั้งแรกหลังพักอาจใช้เวลาสักครู่ ครั้งต่อไปจะเร็วขึ้น':
    'The server is waking up (power-saving mode) — the first load after a rest takes a moment; the next will be quicker',
  'หน้า': 'Page',
  'ก่อนหน้า': 'Previous',
  'บันทึกเอกสารแล้ว แต่ส่งอีเมลแจ้งผู้อนุมัติไม่สำเร็จ — กรุณาแจ้งผู้อนุมัติด้วยตนเอง':
    'The document was saved, but the approver could not be emailed — please tell them yourself',
  'บันทึกเอกสารเรียบร้อยแล้ว': 'Document saved',

  // ── E-Memo: หัวจดหมายและตัวอย่าง ───────────────────────────────────────
  'สำเนาเรียน / CC': 'Copy to / CC',
  'ใส่อีเมลได้ — จะส่ง “เพื่อทราบ” ให้ตอนส่งอนุมัติ (ไม่ต้องอนุมัติ)':
    'Add an email — they are sent a copy for information when it goes for approval, with nothing to approve',
  'ผู้ลงนาม (ผู้เซ็น)': 'Signatory',
  'เว้นว่าง = ผู้จัดทำเซ็นเอง': 'Leave empty and the writer signs',
  'โทร.': 'Tel.',
  'บันทึกข้อความ': 'Memorandum',
  'เลขที่': 'No.',
  '(ระบุเรื่อง)': '(subject)',
  '(เนื้อความของหนังสือจะแสดงที่นี่)': '(the body of the letter appears here)',
  'ผู้จัดทำ:': 'Written by:',
  'สำเนาเรียน :': 'Copy to:',
  'เอกสารที่อ้างถึง': 'Referenced document',
  'เปิดเอกสารเต็ม': 'Open the full document',
  'กำลังโหลดเอกสารที่อ้างถึง…': 'Loading the referenced document…',
  'วันที่รับ:': 'Received:',
  'แผนก:': 'Department:',
  'เรียน:': 'To:',
  'ไม่มีไฟล์หนังสือให้แสดง — กด “เปิดเอกสารเต็ม” เพื่อดูรายละเอียด':
    'No letter file to show — press "Open the full document" for the detail',
  '(ข้อความเดิม — ไม่ได้ลิงก์)': '(as originally typed — not a link)',
  'ค้นหาเลขที่หรือเรื่องของเอกสารในระบบ…': 'Search the system by document number or subject…',
  'กำลังค้นหา…': 'Searching…',

  // ── E-Memo: สำเนาเรียนและหน้าตรวจสอบ ───────────────────────────────────
  'VCB E-Memo · สำเนาเรียน': 'VCB E-Memo · copy',
  'เปิดเอกสารไม่สำเร็จ': 'Could not open the document',
  'หน้านี้เปิดจากลิงก์ในอีเมลสำเนาเรียน — แสดงเฉพาะเอกสารฉบับนี้เท่านั้น และเป็นการดูอย่างเดียว':
    'This page came from a link in a copy email — it shows this one document only, and is read-only',
  'วันที่:': 'Date:',
  'บริษัท:': 'Company:',
  'หนังสือ': 'Letter',
  'เปิด / บันทึกไฟล์': 'Open / save the file',
  'เปิดไฟล์หนังสือไม่สำเร็จ —': 'Could not open the letter —',
  'กำลังโหลดหนังสือ…': 'Loading the letter…',
  'ยังไม่มีไฟล์หนังสือสำหรับเอกสารฉบับนี้': 'There is no letter file for this document yet',
  'กำลังเปิดตาราง…': 'Opening the spreadsheet…',
  'กรุณาดาวน์โหลดไฟล์เพื่อเปิดด้วยโปรแกรม': 'Please download the file to open it in an application',
  'แสดงเพียงบางส่วน (ไฟล์ขนาดใหญ่) — ดาวน์โหลดเพื่อดูข้อมูลทั้งหมด':
    'Showing part of it (the file is large) — download it to see everything',
  'ผู้จัดการโครงการ (ผู้ลงนาม) อนุมัติเป็นลำดับแรก แล้วส่งต่อผู้อนุมัติที่สูงกว่าทีละคน — ระบบส่งอีเมลให้เข้ามาอนุมัติในเว็บ (ทุกคนต้องมีบัญชีในระบบ)':
    'The project manager signs and approves first, then it goes to more senior approvers one at a time — each is emailed to approve in the web app, and everyone needs an account',
  'เหตุผลที่ส่งพิจารณาอีกครั้ง': 'Why it is being resubmitted',
  'เช่น แก้ไขตัวเลขงบประมาณตามที่ท่านให้ความเห็นแล้ว':
    'e.g. the budget figures have been corrected as you asked',
  'ข้อความนี้จะบันทึกในประวัติและแจ้งให้ผู้อนุมัติทราบว่าได้แก้ไขอะไรไปแล้ว':
    'This is recorded in the history and tells the approver what changed',
  'VCB E-Memo · ตรวจสอบเอกสาร': 'VCB E-Memo · document verification',
  'ตรวจสอบไม่สำเร็จ': 'Could not verify',
  'QR หรือลิงก์อาจไม่ถูกต้อง หรือเอกสารถูกลบออกจากระบบแล้ว':
    'The QR code or link may be wrong, or the document has been removed',
  'กำลังตรวจสอบ…': 'Verifying…',
  'หน้านี้แสดงข้อมูลจากระบบ VCB E-Memo โดยตรง เพื่อยืนยันว่าเอกสารเป็นของจริง':
    'This page reads straight from the VCB E-Memo system, to confirm the document is genuine',
  'ประเภท:': 'Type:',
  'การพิจารณา': 'Decisions',
  'ประวัติการดำเนินการ (Audit Trail)': 'Audit trail',
};
